import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { isAppLanguage, type AppLanguage } from "@/lib/localization";

type Language = AppLanguage;

interface LanguageContextValue {
  language:       Language;
  toggleLanguage: () => void;
  isRTL:          boolean;
  t:              (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.dashboard":   "Dashboard",
    "nav.masters":     "Masters",
    "nav.inventory":   "Inventory",
    "nav.procurement": "Procurement",
    "nav.production":  "Production",
    "nav.recipes":     "Recipes",
    "nav.sales":       "Sales",
    "nav.finance":     "Finance",
    "nav.governance":  "Governance",
    "nav.report":      "Report",
    // Topbar
    "topbar.home":    "Home",
    "topbar.signout": "Sign out",
    // Common
    "common.refresh":  "Refresh",
    "common.approve":  "Approve",
    "common.reject":   "Reject",
    "common.save":     "Save",
    "common.cancel":   "Cancel",
    "common.loading":  "Loading…",
    "common.export":   "Export",
    "common.add":      "Add",
    "common.dismiss":  "Dismiss",
    "common.to":       "to",
    "common.noData":   "No data available",
    // Dashboard
    "dashboard.title":              "Dashboard",
    "dashboard.subtitle":           "Enterprise Branch Costing",
    "dashboard.totalSales":         "Total Sales",
    "dashboard.inventoryValue":     "Inventory Value",
    "dashboard.pendingApprovals":   "Pending Approvals",
    "dashboard.branchCount":        "Branch Count",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.quickStats":         "Quick Stats",
    "dashboard.attentionRequired":  "Attention Required",
    "dashboard.noRecentTx":         "No recent transactions",
    "dashboard.allBranches":        "All Branches",
    "dashboard.thisMonth":          "This Month",
    "dashboard.lastMonth":          "Last Month",
    "dashboard.thisYear":           "This Year",
    "dashboard.allTime":            "All Time",
    "dashboard.custom":             "Custom",
    "dashboard.selectBranch":       "Please select a branch",
    "dashboard.exportFailed":       "Export failed",
    "dashboard.exporting":          "Exporting...",
    "dashboard.activeBranches":     "Active Branches",
    "dashboard.avgSalesBranch":     "Avg Sales / Branch",
    "dashboard.totalRevenue":       "Total Revenue",
    "dashboard.pendingItems":       "{count} items are pending approval.",
    "dashboard.noPendingItems":     "No pending items requiring attention.",
    // Approval Queue
    "approval.title":        "Approval Queue",
    "approval.pending":      "pending",
    "approval.empty":        "No pending approvals",
    "approval.loadError":    "Failed to load pending approvals.",
    "approval.actionFailed": "Action failed",
    "approval.id":           "ID",
    "approval.type":         "Type",
    "approval.branch":       "Branch",
    "approval.requestedBy":  "Requested By",
    "approval.requestedAt":  "Requested At",
    "approval.actions":      "Actions",
    // Finance
    "finance.title":             "Finance",
    "finance.subtitle":          "P&L · Expenses · Payroll · Accruals · Budget · Period Controls",
    "finance.selectBranch":      "Select branch...",
    "finance.selectBranchAlert": "Select a branch to load finance data.",
    "finance.periodClosed":      "{branch} is closed through the selected period. No new entries can be posted.",
    "finance.addEntry":          "Add Entry",
    "finance.closePeriod":       "Close Period",
    "finance.closePeriodConfirm":"Close {branch} through {date}?",
    "finance.closePeriodNote":   "Closing prevents new entries from being posted into this branch and period.",
    "finance.closedThrough":     "Close Through *",
    "finance.periodOpen":        "Period Open",
    "finance.periodClosedBadge": "Period Closed",
    "finance.revenueNote":       "Revenue derived from recorded sales · All amounts in EGP",
    "finance.saveFailed":        "Failed to save. Please try again.",
    "finance.closeFailed":       "Failed to close period. Please try again.",
    "finance.selectBranchFirst": "Please select a branch first",
    "finance.amountPositive":    "Amount must be greater than 0",
    "finance.salaryPositive":    "Base salary must be greater than 0",
    "finance.assetRequired":     "Asset name is required",
    "finance.monthsPositive":    "Months must be greater than 0",
    "finance.budgetPositive":    "Budget amount must be greater than 0",
    // Finance — Operations
    "finance.operations":    "Finance Operations",
    "finance.snapshot":      "Financial Snapshot",
    "finance.expense":       "Expense",
    "finance.expenseDesc":   "Record branch spend",
    "finance.payroll":       "Payroll",
    "finance.payrollDesc":   "Save payroll for period",
    "finance.accrual":       "Accrual",
    "finance.accrualDesc":   "Recognize unpaid obligations",
    "finance.depreciation":  "Depreciation",
    "finance.depreciationDesc": "Track asset expense",
    "finance.prepayment":    "Prepayment",
    "finance.prepaymentDesc":"Spread prepaid costs",
    "finance.budget":        "Budget",
    "finance.budgetDesc":    "Set or update targets",
    "finance.setFirstBudget":"Set First Budget",
    "finance.setBudget":     "Set Budget",
    "finance.noBudget":      "No budget set for this period.",
    "finance.noBudgetHint":  "Go to the Budget tab to set targets.",
    "finance.viewFullPL":    "View Full P&L",
    // Finance — Tabs
    "finance.tab.overview":  "Overview",
    "finance.tab.pl":        "P&L Report",
    "finance.tab.budget":    "Budget",
    "finance.tab.activity":  "Activity Log",
    "finance.tab.approvals": "Approvals",
    // Finance — KPIs
    "finance.kpi.revenue":          "Revenue",
    "finance.kpi.grossProfit":      "Gross Profit",
    "finance.kpi.ebitda":           "EBITDA",
    "finance.kpi.totalCosts":       "Total Costs",
    "finance.kpi.netProfit":        "Net Profit",
    "finance.kpi.netLoss":          "Net Loss",
    "finance.kpi.netResult":        "Net Result",
    "finance.kpi.totalBudget":      "Total Budget",
    "finance.kpi.totalActual":      "Total Actual",
    "finance.kpi.totalVariance":    "Total Variance",
    "finance.kpi.foodCostPct":      "Food Cost %",
    "finance.kpi.laborCostPct":     "Labor Cost %",
    "finance.kpi.wasteCost":        "Waste Cost",
    "finance.kpi.pendingApprovals": "Pending Approvals",
    "finance.kpi.periodStatus":     "Period Status",
    "finance.kpi.profitable":       "Profitable",
    "finance.kpi.loss":             "Loss",
    // Finance — P&L
    "finance.pl.title":           "Profit & Loss Statement",
    "finance.pl.exportPdf":       "Export PDF",
    "finance.pl.incomeStatement": "Income Statement",
    "finance.pl.costBreakdown":   "Cost Breakdown",
    "finance.pl.vsBudget":        "vs Budget",
    "finance.pl.netSales":        "Net Sales Revenue",
    "finance.pl.foodCostCogs":    "Food Cost (COGS)",
    "finance.pl.wasteAndDamage":  "Waste & Damage",
    "finance.pl.grossProfit":     "GROSS PROFIT",
    "finance.pl.operatingExp":    "Operating Expenses",
    "finance.pl.ebitda":          "EBITDA (excl. depreciation)",
    "finance.pl.netProfit":       "NET PROFIT",
    "finance.pl.netLoss":         "NET LOSS",
    "finance.pl.keyRatios":       "Key Ratios",
    "finance.pl.costWaterfall":   "Cost Waterfall",
    "finance.pl.foodCost":        "Food Cost",
    "finance.pl.waste":           "Waste",
    "finance.pl.opex":            "OpEx",
    "finance.pl.netResult":       "Net Result",
    "finance.pl.margin":          "margin",
    "finance.pl.benchmark":       "Benchmark",
    "finance.pl.showLess":        "Show less",
    "finance.pl.moreCategories":  "+{count} more categories",
    "finance.pl.insights":        "💡 Actionable Insights",
    "finance.pl.largestCost":     "{cat} is your largest cost at {pct} of operating expenses.",
    "finance.pl.foodCostWarn":    "⚠️ Food cost at {pct} — above the 35% industry benchmark.",
    "finance.pl.laborCostWarn":   "⚠️ Labor cost at {pct} — above the 30% benchmark.",
    "finance.pl.totalOpex":       "Total OpEx",
    "finance.pl.categories":      "Categories",
    "finance.pl.categoriesDesc":  "expense categories tracked",
    "finance.pl.detailedBreakdown":"Detailed Expense Breakdown",
    "finance.pl.noExpenseData":   "No expense data for this period",
    "finance.pl.totalOpexRow":    "Total Operating Expenses",
    // Finance — Budget tab
    "finance.budget.title":    "Budget vs Actual",
    "finance.budget.category": "Category",
    "finance.budget.budget":   "Budget",
    "finance.budget.actual":   "Actual",
    "finance.budget.variance": "Variance",
    "finance.budget.usedPct":  "Used %",
    "finance.budget.progress": "Progress",
    "finance.budget.over":     "over",
    "finance.budget.under":    "under",
    // Finance — Activity tab
    "finance.activity.title":       "Financial Activity Log",
    "finance.activity.exportPdf":   "Export PDF",
    "finance.activity.noActivity":  "No financial activity for this period.",
    "finance.activity.date":        "Date",
    "finance.activity.type":        "Type",
    "finance.activity.description": "Description",
    "finance.activity.amount":      "Amount",
    "finance.activity.notes":       "Notes",
    "finance.activity.total":       "Total ({count} entries)",
    // Finance — Approvals tab
    "finance.approvals.title":       "Pending Approvals",
    "finance.approvals.empty":       "No pending approvals",
    "finance.approvals.reviewed":    "All items have been reviewed.",
    "finance.approvals.approve":     "Approve",
    "finance.approvals.reject":      "Reject",
    "finance.approvals.unknown":     "Unknown branch",
    "finance.approvals.unknownBy":   "Unknown",
    "finance.approvals.requestedBy": "Requested by",
    // Finance — Modals
    "finance.modal.recordExpense":      "Record Expense",
    "finance.modal.recordPayroll":      "Record Payroll",
    "finance.modal.recordAccrual":      "Record Accrual",
    "finance.modal.recordDepreciation": "Record Depreciation",
    "finance.modal.recordPrepayment":   "Record Prepayment",
    "finance.modal.setBudget":          "Set Budget",
    "finance.modal.closePeriod":        "Close Period",
    "finance.modal.date":               "Date *",
    "finance.modal.amount":             "Amount *",
    "finance.modal.category":           "Category *",
    "finance.modal.group":              "Group *",
    "finance.modal.subtype":            "Subtype",
    "finance.modal.notes":              "Notes",
    "finance.modal.employeeGroup":      "Employee Group *",
    "finance.modal.baseSalary":         "Base Salary *",
    "finance.modal.employerBurden":     "Employer Burden",
    "finance.modal.assetName":          "Asset Name *",
    "finance.modal.months":             "Months *",
    "finance.modal.period":             "Period *",
    // Ratios
    "finance.ratio.grossMargin":  "Gross Margin",
    "finance.ratio.netMargin":    "Net Margin",
    "finance.ratio.ebitdaMargin": "EBITDA Margin",
    "finance.ratio.opexRatio":    "OpEx Ratio",
    "finance.ratio.vsPrior":      "vs prior period",

    // ── Inventory Controls ────────────────────────────────────────────────────
    "inv.title":               "Inventory Controls",
    "inv.subtitle":            "Enterprise stock management · costing · compliance",
    "inv.selectBranch":        "Select branch...",
    "inv.selectBranchAlert":   "Select a branch above to load stock data and enable all operations.",
    "inv.closePeriod":         "Close Period",
    "inv.generatePO":          "Generate PO",
    "inv.tab.dashboard":       "Dashboard",
    "inv.tab.rawMaterials":    "Raw Materials",
    "inv.tab.finishedGoods":   "Finished Goods",
    "inv.tab.variance":        "Variance Report",
    "inv.tab.cogs":            "COGS",
    "inv.tab.auditLog":        "Audit Log",
    "inv.kpi.rawValue":        "Raw Materials Value",
    "inv.kpi.fgValue":         "Finished Goods Value",
    "inv.kpi.lowStock":        "Low Stock Items",
    "inv.kpi.negative":        "Negative Stock",
    "inv.kpi.ingredients":     "{n} ingredients",
    "inv.kpi.products":        "{n} products",
    "inv.kpi.requiresReorder": "Requires reorder",
    "inv.kpi.urgentAttention": "Urgent attention",
    "inv.pendingBanner.title": "{n} adjustment pending approval",
    "inv.pendingBanner.titlePlural": "{n} adjustments pending approval",
    "inv.pendingBanner.sub":   "Review and approve or reject flagged stock adjustments",
    "inv.pendingBanner.cta":   "Review Now",
    "inv.ops.title":           "Stock Operations",
    "inv.ops.count":           "Stock Count",
    "inv.ops.countDesc":       "Physical audit log",
    "inv.ops.adjustment":      "Stock Adjustment",
    "inv.ops.adjustmentDesc":  "Correct balance with approval",
    "inv.ops.transfer":        "Stock Transfer",
    "inv.ops.transferDesc":    "Move between branches",
    "inv.ops.opening":         "Opening Stock",
    "inv.ops.openingDesc":     "Record initial inventory",
    "inv.ops.record":          "Record",
    "inv.approvals.title":     "Approval Queue",
    "inv.approvals.pending":   "pending",
    "inv.approvals.empty":     "No pending approvals",
    "inv.approvals.emptySub":  "All adjustments have been reviewed",
    "inv.approvals.approve":   "Approve",
    "inv.approvals.reject":    "Reject",
    "inv.approvals.notePlaceholder": "Add approval note (optional)...",
    "inv.alerts.title":        "Stock Alerts",
    "inv.alerts.createPO":     "Create PO",
    "inv.alerts.allOk":        "All stock levels OK",
    "inv.alerts.noAlerts":     "No alerts for this branch",
    "inv.alerts.critical":     "Critical",
    "inv.alerts.low":          "Low",
    "inv.alerts.negative":     "Negative: {qty} {unit}",
    "inv.alerts.lowDetail":    "Low: {qty} / {reorder} {unit}",
    "inv.snapshots.title":     "Recent Period Snapshots",
    "inv.snapshots.fullCogs":  "Full COGS Report",
    "inv.snapshots.cogs":      "COGS",
    "inv.snapshots.closing":   "Closing Inv.",
    "inv.snapshots.lockedBy":  "Locked by",
    "inv.table.items":         "{n} items",
    "inv.table.totalValue":    "Total Value",
    "inv.table.items2":        "Items",
    "inv.table.negative":      "Negative",
    "inv.table.lowStock":      "Low Stock",
    "inv.table.searchPlaceholder": "Search items...",
    "inv.table.more":          "More",
    "inv.table.group":         "Group:",
    "inv.table.groupNone":     "None",
    "inv.table.groupStatus":   "Status",
    "inv.table.groupUnit":     "Unit",
    "inv.table.sort":          "Sort:",
    "inv.table.sortName":      "Name",
    "inv.table.sortBalance":   "Balance",
    "inv.table.sortValue":     "Value",
    "inv.table.noData":        "No stock data for this branch",
    "inv.table.noMatch":       "No items match your filters.",
    "inv.table.clearFilters":  "Clear filters",
    "inv.table.selectBranch":  "Select a branch to view",
    "inv.table.col.product":   "Product",
    "inv.table.col.ingredient":"Ingredient",
    "inv.table.col.balance":   "Balance",
    "inv.table.col.reorder":   "Reorder",
    "inv.table.col.value":     "Value",
    "inv.table.col.countAudit":"Count Audit",
    "inv.table.col.purchases": "Purchases",
    "inv.table.col.transfers": "Transfers",
    "inv.table.col.opening":   "Opening",
    "inv.table.col.waste":     "Waste/Adj",
    "inv.table.col.variance":  "Variance",
    "inv.table.col.status":    "Status",
    "inv.table.col.lastCount": "Last Count",
    "inv.table.col.diff":      "Diff",
    "inv.table.col.totalRcvd": "Total Rcvd",
    "inv.table.col.in":        "In",
    "inv.table.col.out":       "Out",
    "inv.table.col.openingQty":"Opening Qty",
    "inv.table.col.netAdj":    "Net Adj.",
    "inv.table.col.varPct":    "Var %",
    "inv.table.status.ok":     "OK",
    "inv.table.status.low":    "Low",
    "inv.table.status.negative":"Negative",
    "inv.table.status.loss":   "Loss",
    "inv.table.page":          "Page {page} of {total} · {count} items",
    "inv.table.legend.count":  "Count Audit",
    "inv.table.legend.purchases":"Purchases",
    "inv.table.legend.transfers":"Transfers",
    "inv.table.legend.opening":"Opening",
    "inv.table.legend.waste":  "Waste/Adj.",
    "inv.table.legend.variance":"Variance %",
    "inv.table.legend.hint":   "▶ click row to see flow breakdown",
    "inv.table.orders":        "{n} orders",
    "inv.flow.title":          "Stock Flow Summary",
    "inv.flow.opening":        "Opening Stock",
    "inv.flow.purchases":      "+ Purchases Received",
    "inv.flow.transferIn":     "+ Transfers In",
    "inv.flow.transferOut":    "− Transfers Out",
    "inv.flow.production":     "− Used in Production",
    "inv.flow.adjustments":    "± Other Adjustments",
    "inv.flow.balance":        "= Current Balance",
    "inv.modal.count.title":   "📝 Stock Count",
    "inv.modal.count.sub":     "Physical audit — does not change balance",
    "inv.modal.count.field.ingredient": "Ingredient *",
    "inv.modal.count.field.date":       "Date *",
    "inv.modal.count.field.qty":        "Counted Qty *",
    "inv.modal.count.field.notes":      "Notes",
    "inv.modal.count.hint":    "ℹ️ Count is an audit log only. Use Stock Adjustment to correct the balance.",
    "inv.modal.adj.title":     "⚙️ Stock Adjustment",
    "inv.modal.adj.sub":       "Corrects the inventory balance",
    "inv.modal.adj.field.ingredient": "Ingredient *",
    "inv.modal.adj.field.date":       "Date *",
    "inv.modal.adj.field.delta":      "Qty Delta (+ or −) *",
    "inv.modal.adj.field.deltaHint":  "Negative = write-down, Positive = add stock",
    "inv.modal.adj.field.reason":     "Reason *",
    "inv.modal.adj.field.notes":      "Notes",
    "inv.modal.adj.field.approval":   "Flag for manager approval before applying",
    "inv.modal.adj.reason.waste":     "Waste",
    "inv.modal.adj.reason.damage":    "Damage",
    "inv.modal.adj.reason.theft":     "Theft",
    "inv.modal.adj.reason.recount":   "Recount",
    "inv.modal.adj.reason.spoilage":  "Spoilage",
    "inv.modal.adj.reason.expiry":    "Expiry",
    "inv.modal.adj.reason.prodError": "Production Error",
    "inv.modal.adj.reason.other":     "Other",
    "inv.modal.transfer.title": "↔️ Stock Transfer",
    "inv.modal.transfer.sub":   "Move stock between branches",
    "inv.modal.transfer.field.from":     "From Branch *",
    "inv.modal.transfer.field.to":       "To Branch *",
    "inv.modal.transfer.field.ingredient":"Ingredient *",
    "inv.modal.transfer.field.date":     "Date *",
    "inv.modal.transfer.field.qty":      "Quantity *",
    "inv.modal.transfer.field.notes":    "Notes",
    "inv.modal.opening.title":  "📥 Opening Stock",
    "inv.modal.opening.sub":    "Record initial inventory for a period",
    "inv.modal.opening.field.ingredient":"Ingredient *",
    "inv.modal.opening.field.date":      "Date *",
    "inv.modal.opening.field.qty":       "Quantity *",
    "inv.modal.opening.field.notes":     "Notes",
    "inv.modal.period.title":   "🔒 Close Period",
    "inv.modal.period.sub":     "Lock a period snapshot for COGS calculation",
    "inv.modal.period.preview": "Snapshot Preview",
    "inv.modal.period.closingRaw":  "Closing Raw Materials",
    "inv.modal.period.closingFG":   "Closing Finished Goods",
    "inv.modal.period.totalPurch":  "Total Purchases",
    "inv.modal.period.estCogs":     "Est. COGS",
    "inv.modal.period.field.label": "Period Label *",
    "inv.modal.period.field.labelHint": 'e.g. "May 2025" or "Week 21"',
    "inv.modal.period.field.labelPlaceholder": "e.g. May 2025",
    "inv.modal.period.field.date":  "Close Date *",
    "inv.modal.period.field.notes": "Notes",
    "inv.modal.period.warning":     "This creates an immutable snapshot of current inventory values. It does not modify any stock balances.",
    "inv.err.selectBranch":    "Please select a branch first",
    "inv.err.selectIngredient":"Select an ingredient",
    "inv.err.negativeQty":     "Counted quantity cannot be negative",
    "inv.err.reasonRequired":  "Reason is required",
    "inv.err.sourceBranch":    "Select source branch",
    "inv.err.destBranch":      "Select destination branch",
    "inv.err.sameBranch":      "Source and destination must differ",
    "inv.err.qtyPositive":     "Quantity must be greater than 0",
    "inv.err.periodLabel":     "Period label is required (e.g. May 2025)",
    "inv.err.saveFailed":      "Failed to save. Please try again.",
    "inv.po.title":            "Generate Purchase Order",
    "inv.po.sub":              "{n} items need restocking",
    "inv.po.empty":            "No items need restocking right now",
    "inv.po.orderQty":         "Order qty:",
    "inv.po.selected":         "{n} items selected",
    "inv.po.print":            "Print / Export PO",
    "inv.po.current":          "Current:",
    "inv.po.reorderAt":        "Reorder at:",
    "inv.variance.period":     "Period:",
    "inv.variance.run":        "Run Variance Report",
    "inv.variance.info":       "ℹ️ Variance = Actual Usage − Theoretical Usage · Negative finished goods = sold without production",
    "inv.variance.analyzed":   "Items Analyzed",
    "inv.variance.highShrinkage":"High Shrinkage",
    "inv.variance.highShrinkageSub":">10% variance",
    "inv.variance.totalValue": "Total Shrinkage Value",
    "inv.variance.avg":        "Avg Variance",
    "inv.variance.empty":      "Select a date range and run the report",
    "inv.variance.noData":     "No variance data for this period",
    "inv.variance.col.item":   "Item",
    "inv.variance.col.type":   "Type",
    "inv.variance.col.theoretical":"Theoretical",
    "inv.variance.col.actual": "Actual",
    "inv.variance.col.variance":"Variance",
    "inv.variance.col.variancePct":"Variance %",
    "inv.variance.col.valueAtRisk":"Value at Risk",
    "inv.variance.col.risk":   "Risk Level",
    "inv.variance.type.fg":    "Finished Good",
    "inv.variance.type.ingredient":"Ingredient",
    "inv.variance.risk.critical":"critical",
    "inv.variance.risk.high":  "high",
    "inv.variance.risk.medium":"medium",
    "inv.variance.risk.low":   "low",
    "inv.cogs.period":         "Period:",
    "inv.cogs.showing":        "Showing data for {period}",
    "inv.cogs.noSnapshots":    "No period snapshots found",
    "inv.cogs.noSnapshotsSub": "Accurate COGS requires period-end snapshots. Use the \"Close Period\" button at the end of each month to lock inventory values.",
    "inv.cogs.formula":        "Formula: Opening Balance + Purchases − Closing Balance = COGS",
    "inv.cogs.currentInv":     "Current Inventory Value",
    "inv.cogs.purchases":      "Purchases ({period})",
    "inv.cogs.estimated":      "Estimated COGS",
    "inv.cogs.estimatedSub":   "Opening + Purchases − Closing",
    "inv.cogs.currentInv2":    "Current Inventory",
    "inv.cogs.estThisPeriod":  "Est. COGS This Period",
    "inv.cogs.lockedPeriods":  "Locked Periods",
    "inv.cogs.calcTitle":      "COGS Calculation — {period}",
    "inv.cogs.opening":        "Opening Inventory",
    "inv.cogs.openingNote":    "From last period snapshot",
    "inv.cogs.openingNone":    "No prior snapshot — close a period first",
    "inv.cogs.plusPurchases":  "+ Purchases",
    "inv.cogs.purchasesNote":  "{n} purchases in {period}",
    "inv.cogs.minusClosing":   "− Closing Inventory",
    "inv.cogs.closingNote":    "Current live balance",
    "inv.cogs.result":         "= COGS (Estimated)",
    "inv.cogs.resultNote":     "Estimated — lock period for accuracy",
    "inv.cogs.resultNone":     "Requires opening snapshot",
    "inv.cogs.history":        "Locked Period History",
    "inv.cogs.col.period":     "Period",
    "inv.cogs.col.openingInv": "Opening Inv.",
    "inv.cogs.col.purchases":  "+ Purchases",
    "inv.cogs.col.closingInv": "− Closing Inv.",
    "inv.cogs.col.cogs":       "= COGS",
    "inv.cogs.col.lockedBy":   "Locked By",
    "inv.cogs.col.date":       "Date",
    "inv.audit.searchPlaceholder": "Search by entity, user, or details...",
    "inv.audit.total":         "{n} total entries",
    "inv.audit.shown":         "{n} shown",
    "inv.audit.latest":        "Latest:",
    "inv.audit.empty":         "No audit entries yet",
    "inv.audit.emptySub":      "All inventory changes, approvals, and period closures will appear here",
    "inv.audit.noMatch":       "No entries match your filters.",
    "inv.audit.clearFilters":  "Clear filters",
    "inv.audit.showing":       "Showing 100 of {n} entries",
    "inv.audit.by":            "by",
    "inv.audit.action.all":    "All",
    "inv.audit.action.create": "create",
    "inv.audit.action.approve":"approve",
    "inv.audit.action.reject": "reject",
    "inv.audit.action.adjustment":"adjustment",
    "inv.audit.action.close":  "close",
    "inv.audit.human.create":            "Created",
    "inv.audit.human.approve":           "Approved",
    "inv.audit.human.reject":            "Rejected",
    "inv.audit.human.close_period":      "Period closed",
    "inv.audit.human.adjustment":        "Stock adjusted",
    "inv.audit.human.adjustment_approved":"Adjustment approved",
    "inv.audit.human.adjustment_rejected":"Adjustment rejected",
    "inv.audit.human.create_period_snapshot":"Snapshot locked",
    "inv.audit.entity.sale":             "Sale",
    "inv.audit.entity.purchase":         "Purchase",
    "inv.audit.entity.transfer":         "Transfer",
    "inv.audit.entity.approval_request": "Approval",
    "inv.audit.entity.inventory_movement":"Stock movement",
    "inv.audit.entity.period_closure":   "Period closure",
    "inv.audit.entity.period_snapshot":  "Period snapshot",
    "inv.audit.entity.customer_return":  "Customer return",
    "inv.audit.entity.purchase_return":  "Purchase return",
    "inv.audit.entity.record":           "Record",
    "inv.modal.cancel": "Cancel",
    "inv.modal.save":   "Save",
    "inv.modal.selectIngredient": "Select ingredient...",
    "inv.modal.selectReason":     "Select reason...",
    "inv.modal.selectBranch":     "Select...",
    "inv.modal.notesPlaceholder": "Any remarks...",
    "inv.modal.adjNotesPlaceholder": "Additional details...",
    "inv.modal.transferNotesPlaceholder": "Transfer notes...",
    "inv.modal.openingNotesPlaceholder": "Opening stock notes...",
    "inv.modal.periodNotesPlaceholder":  "Period close notes...",

    // ── Masters ───────────────────────────────────────────────────────────────
    "masters.title":               "Masters",
    "masters.subtitle":            "Manage branches, items, suppliers, users and prices",
    "masters.tab.branches":        "Branches",
    "masters.tab.suppliers":       "Suppliers",
    "masters.tab.items":           "Items",
    "masters.tab.users":           "Users",
    "masters.tab.prices":          "Prices",
    "masters.add.branch":          "Add Branch",
    "masters.add.supplier":        "Add Supplier",
    "masters.add.item":            "Add Item",
    "masters.add.user":            "Add User",
    "masters.add.price":           "Record Price",
    "masters.modal.addBranch":     "Add Branch",
    "masters.modal.addSupplier":   "Add Supplier",
    "masters.modal.addItem":       "Add Item",
    "masters.modal.addUser":       "Add User",
    "masters.modal.recordPrice":   "💰 Record Supplier Price",
    "masters.field.branchName":    "Branch Name *",
    "masters.field.location":      "Location",
    "masters.field.manager":       "Manager Name",
    "masters.field.supplierName":  "Supplier Name *",
    "masters.field.phone":         "Phone",
    "masters.field.notes":         "Notes",
    "masters.field.itemName":      "Item Name *",
    "masters.field.sku":           "SKU",
    "masters.field.category":      "Category",
    "masters.field.unit":          "Unit *",
    "masters.field.standardCost":  "Standard Cost",
    "masters.field.salePrice":     "Sale Price",
    "masters.field.reorderLevel":  "Reorder Level",
    "masters.field.username":      "Username *",
    "masters.field.displayName":   "Display Name *",
    "masters.field.role":          "Role",
    "masters.field.ingredient":    "Ingredient *",
    "masters.field.supplier":      "Supplier *",
    "masters.field.price":         "Price ({currency}) *",
    "masters.field.date":          "Date *",
    "masters.field.ingredientHistory": "Select Ingredient to view price history",
    "masters.cat.rawMaterial":     "Raw Material",
    "masters.cat.finishedGood":    "Finished Good",
    "masters.role.clerk":          "Clerk",
    "masters.role.manager":        "Manager",
    "masters.role.admin":          "Admin",
    "masters.label.active":        "Active",
    "masters.label.noPhone":       "No phone",
    "masters.empty.branches":      "No branches found",
    "masters.empty.suppliers":     "No suppliers found",
    "masters.empty.items":         "No items found",
    "masters.empty.users":         "No users found",
    "masters.empty.prices":        "No price history for this ingredient",
    "masters.empty.selectIngredient": "Select an ingredient above to see its price history",
    "masters.priceHistory.title":  "Supplier Price History",
    "masters.priceHistory.date":   "Date",
    "masters.priceHistory.supplier": "Supplier",
    "masters.priceHistory.price":  "Price ({currency})",
    "masters.priceHistory.notes":  "Notes",
    "masters.defaultPassword":     "Default password will be set to",
    "masters.priceNote":           "This will update the current cost of the ingredient automatically.",
    "masters.confirm.deleteBranch":   "Remove branch \"{name}\"?",
    "masters.confirm.deleteSupplier": "Remove \"{name}\"?",
    "masters.confirm.deleteItem":     "Remove item \"{name}\"?",
    "masters.err.branchName":      "Branch name is required",
    "masters.err.branchSave":      "Failed to save branch. Name may already exist.",
    "masters.err.supplierName":    "Supplier name is required",
    "masters.err.supplierSave":    "Failed to save supplier. Name may already exist.",
    "masters.err.itemRequired":    "Name and unit are required",
    "masters.err.itemSave":        "Failed to save item. Name may already exist.",
    "masters.err.userRequired":    "Username and display name are required",
    "masters.err.userSave":        "Failed to save user. Username may already exist.",
    "masters.err.selectSupplier":  "Select a supplier",
    "masters.err.selectIngredient":"Select an ingredient",
    "masters.err.enterPrice":      "Enter a price",
    "masters.err.priceSave":       "Failed to save price.",
    "masters.ph.branchName":       "e.g. Central Warehouse",
    "masters.ph.location":         "e.g. Cairo, Egypt",
    "masters.ph.manager":          "e.g. Ahmed Hassan",
    "masters.ph.supplierName":     "e.g. Fresh Foods Co.",
    "masters.ph.phone":            "+20 100 000 0000",
    "masters.ph.notes":            "Any additional info...",
    "masters.ph.itemName":         "e.g. Tomatoes",
    "masters.ph.sku":              "RM-001",
    "masters.ph.unit":             "kg / pcs / litre",
    "masters.ph.price":            "0.00",
    "masters.ph.priceNotes":       "e.g. seasonal price, bulk discount...",
    "masters.ph.username":         "e.g. ahmed.hassan",
    "masters.ph.displayName":      "e.g. Ahmed Hassan",
    "masters.ph.selectIngredient": "Select ingredient...",
    "masters.ph.selectSupplier":   "Select supplier...",
    "masters.cancel":              "Cancel",
    "masters.save":                "Save",
    // ── Procurement ──
    "proc.title":               "Procurement",
    "proc.subtitle":            "Purchase orders, returns, and supplier pricing",
    "proc.modal.newPurchase":   "📋 New Purchase Order",
    "proc.modal.return":        "↩️ Purchase Return",
    "proc.field.branch":        "Branch *",
    "proc.field.supplier":      "Supplier *",
    "proc.field.ingredient":    "Ingredient *",
    "proc.field.date":          "Date *",
    "proc.field.quantity":      "Quantity *",
    "proc.field.unitCost":      "Unit Cost ({currency}) *",
    "proc.field.taxAmount":     "Tax Amount ({currency})",
    "proc.field.notes":         "Notes",
    "proc.field.unitCostShort": "Unit Cost *",
    "proc.summary.gross":       "Gross Amount",
    "proc.summary.tax":         "Tax",
    "proc.summary.payable":     "Total Payable",
    "proc.summary.refund":      "Refund Amount",
    "proc.ph.selectBranch":     "Select branch...",
    "proc.ph.selectSupplier":   "Select supplier...",
    "proc.ph.selectIngredient": "Select ingredient...",
    "proc.ph.notes":            "Any additional notes...",
    "proc.ph.returnNotes":      "Reason for return...",
    "proc.err.branch":          "Select a branch",
    "proc.err.supplier":        "Select a supplier",
    "proc.err.ingredient":      "Select an ingredient",
    "proc.err.quantity":        "Enter quantity",
    "proc.err.unitCost":        "Enter unit cost",
    "proc.err.savePurchase":    "Failed to save purchase. Please try again.",
    "proc.err.saveReturn":      "Failed to save return. Please try again.",
    "proc.kpi.totalPurchases":  "Total Purchases",
    "proc.kpi.allTime":         "All time",
    "proc.kpi.thisMonth":       "This Month",
    "proc.kpi.activeSuppliers": "Active Suppliers",
    "proc.kpi.inSystem":        "In your system",
    "proc.ops.title":           "Purchase Operations",
    "proc.ops.purchase":        "Purchase Order",
    "proc.ops.purchaseDesc":    "Record new stock received from supplier",
    "proc.ops.return":          "Purchase Return",
    "proc.ops.returnDesc":      "Return damaged or wrong goods to supplier",
    "proc.ops.record":          "Record",
    "proc.suppliers.title":     "Suppliers",
    "proc.suppliers.empty":     "No suppliers yet",
    "proc.recent.title":        "Recent Purchases",
    "proc.recent.empty":        "No purchases recorded yet",
    "proc.recent.firstCta":     "Record First Purchase",
    "proc.table.date":          "Date",
    "proc.table.branch":        "Branch",
    "proc.table.ingredient":    "Ingredient",
    "proc.table.supplier":      "Supplier",
    "proc.table.qty":           "Qty",
    "proc.table.unitCost":      "Unit Cost",
    "proc.table.total":         "Total",
    "proc.table.status":        "Status",
    "proc.cancel":              "Cancel",
    "proc.save":                "Save",
    // ── Production ──
    "prod.title":                "Production",
    "prod.subtitle":             "Kitchen issues, transfers, and production batches",
    "prod.modal.kitchen":        "🍳 Kitchen Issue",
    "prod.modal.transfer":       "↔️ Stock Transfer",
    "prod.modal.production":     "🏭 Production Batch",
    "prod.field.branch":         "Branch *",
    "prod.field.ingredient":     "Ingredient *",
    "prod.field.date":           "Date *",
    "prod.field.qtyIssued":      "Quantity Issued *",
    "prod.field.station":        "Station *",
    "prod.field.notes":          "Notes",
    "prod.field.fromBranch":     "From Branch *",
    "prod.field.toBranch":       "To Branch *",
    "prod.field.quantity":       "Quantity *",
    "prod.field.product":        "Product (Finished Good) *",
    "prod.field.qtyProduced":    "Quantity Produced *",
    "prod.field.laborCost":      "Direct Labor Cost ({currency})",
    "prod.field.overheadCost":   "Overhead Cost ({currency})",
    "prod.ph.selectBranch":      "Select branch...",
    "prod.ph.selectIngredient":  "Select ingredient...",
    "prod.ph.selectBranchShort": "Select...",
    "prod.ph.selectProduct":     "Select product...",
    "prod.ph.station":           "e.g. Grill Station, Cold Kitchen, Prep",
    "prod.ph.notes":             "Any additional notes...",
    "prod.ph.transferNotes":     "Transfer reason...",
    "prod.ph.productionNotes":   "Production notes...",
    "prod.note.kitchen":         "This will deduct the quantity from the branch stock balance immediately.",
    "prod.note.transfer":        "Stock will be deducted from the source branch and added to the destination branch.",
    "prod.err.branch":           "Select a branch",
    "prod.err.ingredient":       "Select an ingredient",
    "prod.err.quantity":         "Enter quantity",
    "prod.err.station":          "Enter station name",
    "prod.err.fromBranch":       "Select source branch",
    "prod.err.toBranch":         "Select destination branch",
    "prod.err.sameBranch":       "Source and destination must be different",
    "prod.err.product":          "Select a product",
    "prod.err.saveKitchen":      "Failed to save kitchen issue. Please try again.",
    "prod.err.saveTransfer":     "Failed to save transfer. Please try again.",
    "prod.err.saveProduction":   "Failed to save production batch. Please try again.",
    "prod.kpi.recipes":          "Recipes",
    "prod.kpi.recipesDesc":      "Finished goods",
    "prod.kpi.batches":          "Production Batches",
    "prod.kpi.batchesDesc":      "All time",
    "prod.kpi.thisMonth":        "This Month",
    "prod.kpi.thisMonthDesc":    "Production runs",
    "prod.kpi.kitchenIssues":    "Kitchen Issues",
    "prod.kpi.kitchenIssuesDesc":"Total recorded",
    "prod.ops.title":            "Production Operations",
    "prod.ops.kitchen":          "Kitchen Issue",
    "prod.ops.kitchenDesc":      "Issue ingredients to a kitchen station for cooking",
    "prod.ops.transfer":         "Stock Transfer",
    "prod.ops.transferDesc":     "Move stock between branches (e.g. warehouse → branch)",
    "prod.ops.production":       "Production Batch",
    "prod.ops.productionDesc":   "Record actual production run with labor and overhead costs",
    "prod.ops.record":           "Record",
    "prod.products.title":       "Products",
    "prod.products.empty":       "No products yet",
    "prod.recent.title":         "Recent Activity",
    "prod.tab.kitchen":          "Kitchen Issues",
    "prod.tab.production":       "Production",
    "prod.tab.transfers":        "Transfers",
    "prod.kitchen.empty":        "No kitchen issues recorded yet",
    "prod.kitchen.cta":          "Record Kitchen Issue",
    "prod.production.empty":     "No production batches recorded yet",
    "prod.production.cta":       "Record Production Batch",
    "prod.transfers.empty":      "No transfers recorded yet",
    "prod.transfers.cta":        "Record Transfer",
    "prod.table.date":           "Date",
    "prod.table.branch":         "Branch",
    "prod.table.ingredient":     "Ingredient",
    "prod.table.station":        "Station",
    "prod.table.qtyIssued":      "Qty Issued",
    "prod.table.notes":          "Notes",
    "prod.table.product":        "Product",
    "prod.table.quantity":       "Quantity",
    "prod.table.material":       "Material",
    "prod.table.labor":          "Labor",
    "prod.table.totalCost":      "Total Cost",
    "prod.table.from":           "From",
    "prod.table.to":             "To",
    "prod.table.status":         "Status",
    "prod.cancel":               "Cancel",
    "prod.save":                 "Save",

    // ── Recipes ───────────────────────────────────────────────────────────────
    "recipes.title":                   "Recipes",
    "recipes.subtitle":                "Define ingredients and costs for each product",
    "recipes.kpi.totalProducts":       "Total Products",
    "recipes.kpi.totalProductsSub":    "Finished goods",
    "recipes.kpi.ingredients":         "Ingredients",
    "recipes.kpi.ingredientsSub":      "Raw materials",
    "recipes.kpi.tip":                 "💡 Tip",
    "recipes.kpi.tipText":             "Click any product to view its recipe. Use Export PDF to download a formatted recipe sheet.",
    "recipes.search.placeholder":      "Search products by name…",
    "recipes.filter.all":              "All",
    "recipes.filter.hasRecipe":        "✅ Has Recipe",
    "recipes.filter.noRecipe":         "⚠️ No Recipe",
    "recipes.list.title":              "Products & Recipes",
    "recipes.list.showing":            "Showing {shown} of {total} products",
    "recipes.list.empty.search":       "No products match \"{search}\".",
    "recipes.list.empty.default":      "No products found. Add products in Masters first.",
    "recipes.card.clickToLoad":        "Click to load",
    "recipes.card.hasRecipe":          "Has Recipe",
    "recipes.card.noRecipe":           "No Recipe",
    "recipes.card.sale":               "Sale",
    "recipes.card.noRecipeDefined":    "No recipe defined for this product yet.",
    "recipes.card.yield":              "Yield",
    "recipes.card.portion":            "Portion",
    "recipes.card.foodCostPct":        "Food Cost %",
    "recipes.card.rawCostPerPortion":  "Raw Cost / Portion",
    "recipes.card.grossMargin":        "Gross Margin",
    "recipes.card.ingredients":        "Ingredients",
    "recipes.card.col.ingredient":     "Ingredient",
    "recipes.card.col.qtyRequired":    "Qty Required",
    "recipes.card.col.unitCost":       "Unit Cost",
    "recipes.card.col.lineCost":       "Line Cost",
    "recipes.card.notes":              "📝 Notes",
    "recipes.card.addIngredient":      "Add Ingredient",
    "recipes.card.editRecipe":         "Edit Recipe",
    "recipes.card.exportPdf":          "Export PDF",
    "recipes.card.delete":             "Delete",
    "recipes.card.createRecipe":       "Create Recipe",
    "recipes.confirm.deleteMessage":   "This will permanently delete the recipe for \"{name}\" and all its ingredients.",
    "recipes.modal.createTitle":       "📋 Create Recipe — {name}",
    "recipes.modal.editTitle":         "✏️ Edit Recipe — {name}",
    "recipes.modal.addIngredientTitle":"➕ Add Ingredient — {name}",
    "recipes.modal.product":           "Product:",
    "recipes.modal.salePrice":         "Sale price:",
    "recipes.modal.yieldPct":          "Yield % *",
    "recipes.modal.portionSize":       "Portion Size *",
    "recipes.modal.portionUnit":       "Portion Unit *",
    "recipes.modal.notes":             "Notes",
    "recipes.modal.notesPh":           "Recipe notes...",
    "recipes.modal.afterCreate":       "After creating the recipe, you can add ingredients to it.",
    "recipes.modal.ingredient":        "Ingredient *",
    "recipes.modal.selectIngredient":  "Select ingredient...",
    "recipes.modal.qtyRequired":       "Quantity Required per Portion *",
    "recipes.modal.qtyPh":             "e.g. 0.300 for 300g",
    "recipes.modal.lineCost":          "Line cost: {cost} per portion",
    "recipes.modal.qtyNote":           "This is the quantity of this ingredient needed to make one portion of {product}.",
    "recipes.err.yieldRange":          "Yield % must be between 1 and 100",
    "recipes.err.portionSize":         "Portion size must be greater than 0",
    "recipes.err.portionUnit":         "Portion unit is required",
    "recipes.err.saveFailed":          "Failed to save recipe. Please try again.",
    "recipes.err.updateFailed":        "Failed to update recipe.",
    "recipes.err.selectIngredient":    "Select an ingredient",
    "recipes.err.qtyPositive":         "Quantity must be greater than 0",
    "recipes.err.addIngredientFailed": "Failed to add ingredient. It may already be in this recipe.",
    "recipes.unit.plate":              "plate",
    "recipes.unit.box":                "box",
    "recipes.unit.cup":                "cup",
    "recipes.unit.bowl":               "bowl",
    "recipes.unit.serving":            "serving",
    "recipes.unit.piece":              "piece",
    "recipes.unit.kg":                 "kg",
    "recipes.unit.litre":              "litre",
    "recipes.confirm.areYouSure":      "Are you sure?",
    "recipes.confirm.delete":          "Delete",
    "recipes.confirm.cancel":          "Cancel",
    "recipes.modal.save":              "Save",
    "recipes.modal.cancel":            "Cancel",

    // ── Governance ────────────────────────────────────────────────────────────
    "gov.title":                       "Governance",
    "gov.subtitle":                    "Approvals, period closing, and audit controls",
    "gov.metric.pendingApprovals":     "Pending approvals",
    "gov.metric.pendingApprovalsSub":  "Awaiting review",
    "gov.metric.approvedThisMonth":    "Approved this month",
    "gov.metric.approvedThisMonthSub": "94% approval rate",
    "gov.metric.openPeriods":          "Open periods",
    "gov.metric.openPeriodsSub":       "Current: April 2026",
    "gov.ops.title":                   "Governance operations",
    "gov.ops.pendingApprovals":        "Pending approvals",
    "gov.ops.pendingApprovalsDesc":    "Review and approve pending transactions",
    "gov.ops.periodClosing":           "Period closing",
    "gov.ops.periodClosingDesc":       "Close accounting period",
    "gov.ops.auditTrail":              "Audit trail",
    "gov.ops.auditTrailDesc":          "View transaction history and changes",
    "gov.ops.budgetManagement":        "Budget management",
    "gov.ops.budgetManagementDesc":    "Set and monitor budgets",
    "gov.approvalStatus.title":        "Approval status",
    "gov.approvalStatus.pending":      "pending",
    "gov.approvalStatus.approved":     "approved",
    "gov.status.purchases":            "Purchases",
    "gov.status.expenses":             "Expenses",
    "gov.status.adjustments":          "Adjustments",
    "gov.status.transfers":            "Transfers",
    "gov.pending.title":               "Pending approvals",
    "gov.pending.submittedBy":         "Submitted by",
    "gov.pending.reject":              "Reject",
    "gov.pending.approve":             "Approve",
    "gov.approvalType.purchase":       "Purchase order",
    "gov.approvalType.expense":        "Expense",
    "gov.approvalType.stockAdj":       "Stock adjustment",
    "gov.approvalType.transfer":       "Transfer",
    "gov.role.manager":                "Manager",
    "gov.role.admin":                  "Admin",
    "gov.role.accountant":             "Accountant",
    "gov.period.current":              "Current period: April 2026",
    "gov.period.note":                 "Period is open. All transactions are being recorded. Close the period when all entries are complete.",
    "gov.period.close":                "Close period",
    "gov.period.closed":               "Period closed: April 2026",
    "gov.period.closedNote":           "This period has been locked. No new entries can be posted.",
    "gov.period.closedBadge":          "Closed",
    "gov.pending.allReviewed":         "All items have been reviewed.",
    "gov.pending.approved":            "Approved",
    "gov.pending.rejected":            "Rejected",
    "gov.metric.openPeriodsClosed":    "No open periods",
  },

  ar: {
    // Nav
    "nav.dashboard":   "لوحة التحكم",
    "nav.masters":     "البيانات الأساسية",
    "nav.inventory":   "المخزون",
    "nav.procurement": "المشتريات",
    "nav.production":  "الإنتاج",
    "nav.recipes":     "الوصفات",
    "nav.sales":       "المبيعات",
    "nav.finance":     "المالية",
    "nav.governance":  "الحوكمة",
    "nav.report":      "التقارير",
    // Topbar
    "topbar.home":    "الرئيسية",
    "topbar.signout": "تسجيل الخروج",
    // Common
    "common.refresh":  "تحديث",
    "common.approve":  "موافقة",
    "common.reject":   "رفض",
    "common.save":     "حفظ",
    "common.cancel":   "إلغاء",
    "common.loading":  "جارٍ التحميل…",
    "common.export":   "تصدير",
    "common.add":      "إضافة",
    "common.dismiss":  "إغلاق",
    "common.to":       "إلى",
    "common.noData":   "لا توجد بيانات",
    // Dashboard
    "dashboard.title":              "لوحة التحكم",
    "dashboard.subtitle":           "نظام تكاليف الفروع",
    "dashboard.totalSales":         "إجمالي المبيعات",
    "dashboard.inventoryValue":     "قيمة المخزون",
    "dashboard.pendingApprovals":   "الموافقات المعلقة",
    "dashboard.branchCount":        "عدد الفروع",
    "dashboard.recentTransactions": "المعاملات الأخيرة",
    "dashboard.quickStats":         "إحصائيات سريعة",
    "dashboard.attentionRequired":  "يتطلب الانتباه",
    "dashboard.noRecentTx":         "لا توجد معاملات حديثة",
    "dashboard.allBranches":        "جميع الفروع",
    "dashboard.thisMonth":          "هذا الشهر",
    "dashboard.lastMonth":          "الشهر الماضي",
    "dashboard.thisYear":           "هذا العام",
    "dashboard.allTime":            "كل الوقت",
    "dashboard.custom":             "مخصص",
    "dashboard.selectBranch":       "الرجاء اختيار فرع",
    "dashboard.exportFailed":       "فشل التصدير",
    "dashboard.exporting":          "جارٍ التصدير...",
    "dashboard.activeBranches":     "الفروع النشطة",
    "dashboard.avgSalesBranch":     "متوسط المبيعات / فرع",
    "dashboard.totalRevenue":       "إجمالي الإيرادات",
    "dashboard.pendingItems":       "{count} عناصر بانتظار الموافقة.",
    "dashboard.noPendingItems":     "لا توجد عناصر تتطلب الانتباه.",
    // Approval Queue
    "approval.title":        "قائمة الموافقات",
    "approval.pending":      "معلّق",
    "approval.empty":        "لا توجد موافقات معلّقة",
    "approval.loadError":    "فشل تحميل الموافقات المعلّقة.",
    "approval.actionFailed": "فشل الإجراء",
    "approval.id":           "الرقم",
    "approval.type":         "النوع",
    "approval.branch":       "الفرع",
    "approval.requestedBy":  "طُلب بواسطة",
    "approval.requestedAt":  "وقت الطلب",
    "approval.actions":      "الإجراءات",
    // Finance
    "finance.title":             "المالية",
    "finance.subtitle":          "الأرباح والخسائر · المصروفات · الرواتب · المستحقات · الميزانية",
    "finance.selectBranch":      "اختر فرعاً...",
    "finance.selectBranchAlert": "اختر فرعاً لتحميل البيانات المالية.",
    "finance.periodClosed":      "{branch} مغلق حتى الفترة المحددة. لا يمكن إضافة قيود جديدة.",
    "finance.addEntry":          "إضافة قيد",
    "finance.closePeriod":       "إغلاق الفترة",
    "finance.closePeriodConfirm":"إغلاق {branch} حتى {date}؟",
    "finance.closePeriodNote":   "الإغلاق يمنع إضافة قيود جديدة لهذا الفرع والفترة.",
    "finance.closedThrough":     "الإغلاق حتى *",
    "finance.periodOpen":        "الفترة مفتوحة",
    "finance.periodClosedBadge": "الفترة مغلقة",
    "finance.revenueNote":       "الإيرادات مستخرجة من المبيعات المسجلة · جميع المبالغ بالجنيه المصري",
    "finance.saveFailed":        "فشل الحفظ. حاول مرة أخرى.",
    "finance.closeFailed":       "فشل إغلاق الفترة. حاول مرة أخرى.",
    "finance.selectBranchFirst": "الرجاء اختيار فرع أولاً",
    "finance.amountPositive":    "يجب أن يكون المبلغ أكبر من صفر",
    "finance.salaryPositive":    "يجب أن يكون الراتب الأساسي أكبر من صفر",
    "finance.assetRequired":     "اسم الأصل مطلوب",
    "finance.monthsPositive":    "يجب أن تكون الأشهر أكبر من صفر",
    "finance.budgetPositive":    "يجب أن يكون مبلغ الميزانية أكبر من صفر",
    // Finance — Operations
    "finance.operations":    "العمليات المالية",
    "finance.snapshot":      "لقطة مالية",
    "finance.expense":       "مصروف",
    "finance.expenseDesc":   "تسجيل مصروفات الفرع",
    "finance.payroll":       "رواتب",
    "finance.payrollDesc":   "حفظ كشف الرواتب للفترة",
    "finance.accrual":       "مستحقات",
    "finance.accrualDesc":   "الاعتراف بالالتزامات غير المدفوعة",
    "finance.depreciation":  "إهلاك",
    "finance.depreciationDesc": "تتبع مصروف الأصول",
    "finance.prepayment":    "دفعة مقدمة",
    "finance.prepaymentDesc":"توزيع التكاليف المدفوعة مسبقاً",
    "finance.budget":        "الميزانية",
    "finance.budgetDesc":    "تعيين أو تحديث الأهداف",
    "finance.setFirstBudget":"تعيين أول ميزانية",
    "finance.setBudget":     "تعيين الميزانية",
    "finance.noBudget":      "لم يتم تعيين ميزانية لهذه الفترة.",
    "finance.noBudgetHint":  "اذهب إلى تبويب الميزانية لتعيين الأهداف.",
    "finance.viewFullPL":    "عرض كامل الأرباح والخسائر",
    // Finance — Tabs
    "finance.tab.overview":  "نظرة عامة",
    "finance.tab.pl":        "تقرير الأرباح والخسائر",
    "finance.tab.budget":    "الميزانية",
    "finance.tab.activity":  "سجل النشاط",
    "finance.tab.approvals": "الموافقات",
    // Finance — KPIs
    "finance.kpi.revenue":          "الإيرادات",
    "finance.kpi.grossProfit":      "إجمالي الربح",
    "finance.kpi.ebitda":           "EBITDA",
    "finance.kpi.totalCosts":       "إجمالي التكاليف",
    "finance.kpi.netProfit":        "صافي الربح",
    "finance.kpi.netLoss":          "صافي الخسارة",
    "finance.kpi.netResult":        "صافي النتيجة",
    "finance.kpi.totalBudget":      "إجمالي الميزانية",
    "finance.kpi.totalActual":      "إجمالي الفعلي",
    "finance.kpi.totalVariance":    "إجمالي الفارق",
    "finance.kpi.foodCostPct":      "نسبة تكلفة الغذاء",
    "finance.kpi.laborCostPct":     "نسبة تكلفة العمالة",
    "finance.kpi.wasteCost":        "تكلفة الهدر",
    "finance.kpi.pendingApprovals": "الموافقات المعلقة",
    "finance.kpi.periodStatus":     "حالة الفترة",
    "finance.kpi.profitable":       "رابح",
    "finance.kpi.loss":             "خسارة",
    // Finance — P&L
    "finance.pl.title":           "قائمة الأرباح والخسائر",
    "finance.pl.exportPdf":       "تصدير PDF",
    "finance.pl.incomeStatement": "قائمة الدخل",
    "finance.pl.costBreakdown":   "تفاصيل التكاليف",
    "finance.pl.vsBudget":        "مقارنة بالميزانية",
    "finance.pl.netSales":        "صافي إيرادات المبيعات",
    "finance.pl.foodCostCogs":    "تكلفة الغذاء (COGS)",
    "finance.pl.wasteAndDamage":  "الهدر والتلف",
    "finance.pl.grossProfit":     "إجمالي الربح",
    "finance.pl.operatingExp":    "المصروفات التشغيلية",
    "finance.pl.ebitda":          "EBITDA (باستثناء الإهلاك)",
    "finance.pl.netProfit":       "صافي الربح",
    "finance.pl.netLoss":         "صافي الخسارة",
    "finance.pl.keyRatios":       "المؤشرات الرئيسية",
    "finance.pl.costWaterfall":   "شلال التكاليف",
    "finance.pl.foodCost":        "تكلفة الغذاء",
    "finance.pl.waste":           "الهدر",
    "finance.pl.opex":            "المصروفات التشغيلية",
    "finance.pl.netResult":       "النتيجة الصافية",
    "finance.pl.margin":          "هامش",
    "finance.pl.benchmark":       "المعيار",
    "finance.pl.showLess":        "عرض أقل",
    "finance.pl.moreCategories":  "+{count} فئات إضافية",
    "finance.pl.insights":        "💡 رؤى قابلة للتنفيذ",
    "finance.pl.largestCost":     "{cat} هي أكبر تكلفة بنسبة {pct} من المصروفات التشغيلية.",
    "finance.pl.foodCostWarn":    "⚠️ تكلفة الغذاء عند {pct} — تتجاوز المعيار الصناعي 35%.",
    "finance.pl.laborCostWarn":   "⚠️ تكلفة العمالة عند {pct} — تتجاوز المعيار 30%.",
    "finance.pl.totalOpex":       "إجمالي المصروفات التشغيلية",
    "finance.pl.categories":      "الفئات",
    "finance.pl.categoriesDesc":  "فئات المصروفات المتتبعة",
    "finance.pl.detailedBreakdown":"تفصيل المصروفات",
    "finance.pl.noExpenseData":   "لا توجد بيانات مصروفات لهذه الفترة",
    "finance.pl.totalOpexRow":    "إجمالي المصروفات التشغيلية",
    // Finance — Budget tab
    "finance.budget.title":    "الميزانية مقابل الفعلي",
    "finance.budget.category": "الفئة",
    "finance.budget.budget":   "الميزانية",
    "finance.budget.actual":   "الفعلي",
    "finance.budget.variance": "الفارق",
    "finance.budget.usedPct":  "نسبة الاستخدام",
    "finance.budget.progress": "التقدم",
    "finance.budget.over":     "زيادة",
    "finance.budget.under":    "نقص",
    // Finance — Activity tab
    "finance.activity.title":       "سجل النشاط المالي",
    "finance.activity.exportPdf":   "تصدير PDF",
    "finance.activity.noActivity":  "لا يوجد نشاط مالي لهذه الفترة.",
    "finance.activity.date":        "التاريخ",
    "finance.activity.type":        "النوع",
    "finance.activity.description": "الوصف",
    "finance.activity.amount":      "المبلغ",
    "finance.activity.notes":       "ملاحظات",
    "finance.activity.total":       "الإجمالي ({count} قيد)",
    // Finance — Approvals tab
    "finance.approvals.title":       "الموافقات المعلقة",
    "finance.approvals.empty":       "لا توجد موافقات معلقة",
    "finance.approvals.reviewed":    "تمت مراجعة جميع العناصر.",
    "finance.approvals.approve":     "موافقة",
    "finance.approvals.reject":      "رفض",
    "finance.approvals.unknown":     "فرع غير معروف",
    "finance.approvals.unknownBy":   "غير معروف",
    "finance.approvals.requestedBy": "طُلب بواسطة",
    // Finance — Modals
    "finance.modal.recordExpense":      "تسجيل مصروف",
    "finance.modal.recordPayroll":      "تسجيل رواتب",
    "finance.modal.recordAccrual":      "تسجيل مستحقات",
    "finance.modal.recordDepreciation": "تسجيل إهلاك",
    "finance.modal.recordPrepayment":   "تسجيل دفعة مقدمة",
    "finance.modal.setBudget":          "تعيين الميزانية",
    "finance.modal.closePeriod":        "إغلاق الفترة",
    "finance.modal.date":               "التاريخ *",
    "finance.modal.amount":             "المبلغ *",
    "finance.modal.category":           "الفئة *",
    "finance.modal.group":              "المجموعة *",
    "finance.modal.subtype":            "النوع الفرعي",
    "finance.modal.notes":              "ملاحظات",
    "finance.modal.employeeGroup":      "مجموعة الموظفين *",
    "finance.modal.baseSalary":         "الراتب الأساسي *",
    "finance.modal.employerBurden":     "أعباء صاحب العمل",
    "finance.modal.assetName":          "اسم الأصل *",
    "finance.modal.months":             "الأشهر *",
    "finance.modal.period":             "الفترة *",
    // Ratios
    "finance.ratio.grossMargin":  "هامش الربح الإجمالي",
    "finance.ratio.netMargin":    "هامش الربح الصافي",
    "finance.ratio.ebitdaMargin": "هامش EBITDA",
    "finance.ratio.opexRatio":    "نسبة المصروفات التشغيلية",
    "finance.ratio.vsPrior":      "مقارنة بالفترة السابقة",

    // ── Inventory Controls ────────────────────────────────────────────────────
    "inv.title":               "ضوابط المخزون",
    "inv.subtitle":            "إدارة المخزون المؤسسي · التكاليف · الامتثال",
    "inv.selectBranch":        "اختر فرعاً...",
    "inv.selectBranchAlert":   "اختر فرعاً لتحميل بيانات المخزون وتفعيل جميع العمليات.",
    "inv.closePeriod":         "إغلاق الفترة",
    "inv.generatePO":          "إنشاء أمر شراء",
    "inv.tab.dashboard":       "لوحة التحكم",
    "inv.tab.rawMaterials":    "المواد الخام",
    "inv.tab.finishedGoods":   "المنتجات النهائية",
    "inv.tab.variance":        "تقرير الانحراف",
    "inv.tab.cogs":            "تكلفة البضاعة المباعة",
    "inv.tab.auditLog":        "سجل المراجعة",
    "inv.kpi.rawValue":        "قيمة المواد الخام",
    "inv.kpi.fgValue":         "قيمة المنتجات النهائية",
    "inv.kpi.lowStock":        "عناصر منخفضة المخزون",
    "inv.kpi.negative":        "مخزون سالب",
    "inv.kpi.ingredients":     "{n} مكون",
    "inv.kpi.products":        "{n} منتج",
    "inv.kpi.requiresReorder": "يحتاج إعادة طلب",
    "inv.kpi.urgentAttention": "يحتاج اهتماماً عاجلاً",
    "inv.pendingBanner.title":       "{n} تسوية بانتظار الموافقة",
    "inv.pendingBanner.titlePlural": "{n} تسويات بانتظار الموافقة",
    "inv.pendingBanner.sub":   "راجع وافق أو ارفض تسويات المخزون المُعلَّمة",
    "inv.pendingBanner.cta":   "مراجعة الآن",
    "inv.ops.title":           "عمليات المخزون",
    "inv.ops.count":           "جرد المخزون",
    "inv.ops.countDesc":       "سجل مراجعة مادي",
    "inv.ops.adjustment":      "تسوية المخزون",
    "inv.ops.adjustmentDesc":  "تصحيح الرصيد مع الموافقة",
    "inv.ops.transfer":        "تحويل المخزون",
    "inv.ops.transferDesc":    "نقل بين الفروع",
    "inv.ops.opening":         "مخزون الافتتاح",
    "inv.ops.openingDesc":     "تسجيل المخزون الأولي",
    "inv.ops.record":          "تسجيل",
    "inv.approvals.title":     "قائمة الموافقات",
    "inv.approvals.pending":   "معلّق",
    "inv.approvals.empty":     "لا توجد موافقات معلّقة",
    "inv.approvals.emptySub":  "تمت مراجعة جميع التسويات",
    "inv.approvals.approve":   "موافقة",
    "inv.approvals.reject":    "رفض",
    "inv.approvals.notePlaceholder": "أضف ملاحظة موافقة (اختياري)...",
    "inv.alerts.title":        "تنبيهات المخزون",
    "inv.alerts.createPO":     "إنشاء أمر شراء",
    "inv.alerts.allOk":        "جميع مستويات المخزون مقبولة",
    "inv.alerts.noAlerts":     "لا تنبيهات لهذا الفرع",
    "inv.alerts.critical":     "حرج",
    "inv.alerts.low":          "منخفض",
    "inv.alerts.negative":     "سالب: {qty} {unit}",
    "inv.alerts.lowDetail":    "منخفض: {qty} / {reorder} {unit}",
    "inv.snapshots.title":     "لقطات الفترات الأخيرة",
    "inv.snapshots.fullCogs":  "تقرير تكلفة البضاعة المباعة الكامل",
    "inv.snapshots.cogs":      "تكلفة البضاعة المباعة",
    "inv.snapshots.closing":   "مخزون الإغلاق",
    "inv.snapshots.lockedBy":  "مُقفَل بواسطة",
    "inv.table.items":         "{n} عنصر",
    "inv.table.totalValue":    "القيمة الإجمالية",
    "inv.table.items2":        "العناصر",
    "inv.table.negative":      "سالب",
    "inv.table.lowStock":      "منخفض",
    "inv.table.searchPlaceholder": "ابحث عن عناصر...",
    "inv.table.more":          "المزيد",
    "inv.table.group":         "تجميع:",
    "inv.table.groupNone":     "بلا",
    "inv.table.groupStatus":   "الحالة",
    "inv.table.groupUnit":     "الوحدة",
    "inv.table.sort":          "ترتيب:",
    "inv.table.sortName":      "الاسم",
    "inv.table.sortBalance":   "الرصيد",
    "inv.table.sortValue":     "القيمة",
    "inv.table.noData":        "لا توجد بيانات مخزون لهذا الفرع",
    "inv.table.noMatch":       "لا توجد عناصر تطابق الفلاتر.",
    "inv.table.clearFilters":  "مسح الفلاتر",
    "inv.table.selectBranch":  "اختر فرعاً للعرض",
    "inv.table.col.product":   "المنتج",
    "inv.table.col.ingredient":"المكوّن",
    "inv.table.col.balance":   "الرصيد",
    "inv.table.col.reorder":   "نقطة الإعادة",
    "inv.table.col.value":     "القيمة",
    "inv.table.col.countAudit":"مراجعة الجرد",
    "inv.table.col.purchases": "المشتريات",
    "inv.table.col.transfers": "التحويلات",
    "inv.table.col.opening":   "الافتتاح",
    "inv.table.col.waste":     "الهدر/التسوية",
    "inv.table.col.variance":  "الانحراف",
    "inv.table.col.status":    "الحالة",
    "inv.table.col.lastCount": "آخر جرد",
    "inv.table.col.diff":      "الفرق",
    "inv.table.col.totalRcvd": "إجمالي المستلم",
    "inv.table.col.in":        "داخل",
    "inv.table.col.out":       "خارج",
    "inv.table.col.openingQty":"كمية الافتتاح",
    "inv.table.col.netAdj":    "صافي التسوية",
    "inv.table.col.varPct":    "% الانحراف",
    "inv.table.status.ok":     "مقبول",
    "inv.table.status.low":    "منخفض",
    "inv.table.status.negative":"سالب",
    "inv.table.status.loss":   "خسارة",
    "inv.table.page":          "صفحة {page} من {total} · {count} عنصر",
    "inv.table.legend.count":  "مراجعة الجرد",
    "inv.table.legend.purchases":"المشتريات",
    "inv.table.legend.transfers":"التحويلات",
    "inv.table.legend.opening":"الافتتاح",
    "inv.table.legend.waste":  "الهدر/التسوية",
    "inv.table.legend.variance":"% الانحراف",
    "inv.table.legend.hint":   "▶ انقر على الصف لعرض تفاصيل التدفق",
    "inv.table.orders":        "{n} طلبات",
    "inv.flow.title":          "ملخص تدفق المخزون",
    "inv.flow.opening":        "مخزون الافتتاح",
    "inv.flow.purchases":      "+ المشتريات المستلمة",
    "inv.flow.transferIn":     "+ التحويلات الواردة",
    "inv.flow.transferOut":    "− التحويلات الصادرة",
    "inv.flow.production":     "− المستخدم في الإنتاج",
    "inv.flow.adjustments":    "± تسويات أخرى",
    "inv.flow.balance":        "= الرصيد الحالي",
    "inv.modal.count.title":   "📝 جرد المخزون",
    "inv.modal.count.sub":     "مراجعة مادية — لا تغير الرصيد",
    "inv.modal.count.field.ingredient": "المكوّن *",
    "inv.modal.count.field.date":       "التاريخ *",
    "inv.modal.count.field.qty":        "الكمية المعدودة *",
    "inv.modal.count.field.notes":      "ملاحظات",
    "inv.modal.count.hint":    "ℹ️ الجرد سجل مراجعة فقط. استخدم تسوية المخزون لتصحيح الرصيد.",
    "inv.modal.adj.title":     "⚙️ تسوية المخزون",
    "inv.modal.adj.sub":       "تصحيح رصيد المخزون",
    "inv.modal.adj.field.ingredient": "المكوّن *",
    "inv.modal.adj.field.date":       "التاريخ *",
    "inv.modal.adj.field.delta":      "فرق الكمية (+ أو −) *",
    "inv.modal.adj.field.deltaHint":  "سالب = شطب، موجب = إضافة مخزون",
    "inv.modal.adj.field.reason":     "السبب *",
    "inv.modal.adj.field.notes":      "ملاحظات",
    "inv.modal.adj.field.approval":   "تعليم للموافقة الإدارية قبل التطبيق",
    "inv.modal.adj.reason.waste":     "هدر",
    "inv.modal.adj.reason.damage":    "تلف",
    "inv.modal.adj.reason.theft":     "سرقة",
    "inv.modal.adj.reason.recount":   "إعادة جرد",
    "inv.modal.adj.reason.spoilage":  "فساد",
    "inv.modal.adj.reason.expiry":    "انتهاء صلاحية",
    "inv.modal.adj.reason.prodError": "خطأ في الإنتاج",
    "inv.modal.adj.reason.other":     "أخرى",
    "inv.modal.transfer.title": "↔️ تحويل المخزون",
    "inv.modal.transfer.sub":   "نقل المخزون بين الفروع",
    "inv.modal.transfer.field.from":     "من الفرع *",
    "inv.modal.transfer.field.to":       "إلى الفرع *",
    "inv.modal.transfer.field.ingredient":"المكوّن *",
    "inv.modal.transfer.field.date":     "التاريخ *",
    "inv.modal.transfer.field.qty":      "الكمية *",
    "inv.modal.transfer.field.notes":    "ملاحظات",
    "inv.modal.opening.title":  "📥 مخزون الافتتاح",
    "inv.modal.opening.sub":    "تسجيل المخزون الأولي للفترة",
    "inv.modal.opening.field.ingredient":"المكوّن *",
    "inv.modal.opening.field.date":      "التاريخ *",
    "inv.modal.opening.field.qty":       "الكمية *",
    "inv.modal.opening.field.notes":     "ملاحظات",
    "inv.modal.period.title":   "🔒 إغلاق الفترة",
    "inv.modal.period.sub":     "قفل لقطة الفترة لحساب تكلفة البضاعة المباعة",
    "inv.modal.period.preview": "معاينة اللقطة",
    "inv.modal.period.closingRaw":  "إغلاق المواد الخام",
    "inv.modal.period.closingFG":   "إغلاق المنتجات النهائية",
    "inv.modal.period.totalPurch":  "إجمالي المشتريات",
    "inv.modal.period.estCogs":     "تكلفة البضاعة المباعة التقديرية",
    "inv.modal.period.field.label": "تسمية الفترة *",
    "inv.modal.period.field.labelHint": 'مثل: "مايو 2025" أو "الأسبوع 21"',
    "inv.modal.period.field.labelPlaceholder": "مثل: مايو 2025",
    "inv.modal.period.field.date":  "تاريخ الإغلاق *",
    "inv.modal.period.field.notes": "ملاحظات",
    "inv.modal.period.warning":     "يُنشئ هذا لقطة ثابتة لقيم المخزون الحالية. لا يُعدّل أي أرصدة مخزون.",
    "inv.err.selectBranch":    "الرجاء اختيار فرع أولاً",
    "inv.err.selectIngredient":"اختر مكوناً",
    "inv.err.negativeQty":     "لا يمكن أن تكون الكمية المعدودة سالبة",
    "inv.err.reasonRequired":  "السبب مطلوب",
    "inv.err.sourceBranch":    "اختر الفرع المصدر",
    "inv.err.destBranch":      "اختر الفرع الوجهة",
    "inv.err.sameBranch":      "يجب أن يختلف المصدر عن الوجهة",
    "inv.err.qtyPositive":     "يجب أن تكون الكمية أكبر من صفر",
    "inv.err.periodLabel":     "تسمية الفترة مطلوبة (مثل: مايو 2025)",
    "inv.err.saveFailed":      "فشل الحفظ. حاول مرة أخرى.",
    "inv.po.title":            "إنشاء أمر شراء",
    "inv.po.sub":              "{n} عناصر تحتاج إعادة تخزين",
    "inv.po.empty":            "لا توجد عناصر تحتاج إعادة تخزين الآن",
    "inv.po.orderQty":         "كمية الطلب:",
    "inv.po.selected":         "{n} عناصر محددة",
    "inv.po.print":            "طباعة / تصدير أمر الشراء",
    "inv.po.current":          "الحالي:",
    "inv.po.reorderAt":        "إعادة الطلب عند:",
    "inv.variance.period":     "الفترة:",
    "inv.variance.run":        "تشغيل تقرير الانحراف",
    "inv.variance.info":       "ℹ️ الانحراف = الاستخدام الفعلي − الاستخدام النظري · المنتجات النهائية السالبة = مُبيعة بدون إنتاج",
    "inv.variance.analyzed":   "العناصر المحللة",
    "inv.variance.highShrinkage":"انكماش عالٍ",
    "inv.variance.highShrinkageSub":">10% انحراف",
    "inv.variance.totalValue": "إجمالي قيمة الانكماش",
    "inv.variance.avg":        "متوسط الانحراف",
    "inv.variance.empty":      "اختر نطاقاً زمنياً وشغّل التقرير",
    "inv.variance.noData":     "لا توجد بيانات انحراف لهذه الفترة",
    "inv.variance.col.item":   "العنصر",
    "inv.variance.col.type":   "النوع",
    "inv.variance.col.theoretical":"النظري",
    "inv.variance.col.actual": "الفعلي",
    "inv.variance.col.variance":"الانحراف",
    "inv.variance.col.variancePct":"% الانحراف",
    "inv.variance.col.valueAtRisk":"القيمة المعرضة للخطر",
    "inv.variance.col.risk":   "مستوى الخطر",
    "inv.variance.type.fg":    "منتج نهائي",
    "inv.variance.type.ingredient":"مكوّن",
    "inv.variance.risk.critical":"حرج",
    "inv.variance.risk.high":  "عالٍ",
    "inv.variance.risk.medium":"متوسط",
    "inv.variance.risk.low":   "منخفض",
    "inv.cogs.period":         "الفترة:",
    "inv.cogs.showing":        "عرض بيانات {period}",
    "inv.cogs.noSnapshots":    "لم يتم العثور على لقطات فترة",
    "inv.cogs.noSnapshotsSub": "تتطلب تكلفة البضاعة المباعة الدقيقة لقطات نهاية فترة. استخدم زر \"إغلاق الفترة\" في نهاية كل شهر لقفل قيم المخزون.",
    "inv.cogs.formula":        "المعادلة: مخزون الافتتاح + المشتريات − مخزون الإغلاق = تكلفة البضاعة المباعة",
    "inv.cogs.currentInv":     "قيمة المخزون الحالية",
    "inv.cogs.purchases":      "المشتريات ({period})",
    "inv.cogs.estimated":      "تكلفة البضاعة المباعة التقديرية",
    "inv.cogs.estimatedSub":   "افتتاح + مشتريات − إغلاق",
    "inv.cogs.currentInv2":    "المخزون الحالي",
    "inv.cogs.estThisPeriod":  "تكلفة البضاعة المباعة التقديرية للفترة",
    "inv.cogs.lockedPeriods":  "الفترات المقفولة",
    "inv.cogs.calcTitle":      "حساب تكلفة البضاعة المباعة — {period}",
    "inv.cogs.opening":        "مخزون الافتتاح",
    "inv.cogs.openingNote":    "من لقطة الفترة الأخيرة",
    "inv.cogs.openingNone":    "لا توجد لقطة سابقة — أغلق فترة أولاً",
    "inv.cogs.plusPurchases":  "+ المشتريات",
    "inv.cogs.purchasesNote":  "{n} مشتريات في {period}",
    "inv.cogs.minusClosing":   "− مخزون الإغلاق",
    "inv.cogs.closingNote":    "الرصيد الحالي المباشر",
    "inv.cogs.result":         "= تكلفة البضاعة المباعة (تقديري)",
    "inv.cogs.resultNote":     "تقديري — أقفل الفترة للدقة",
    "inv.cogs.resultNone":     "يتطلب لقطة افتتاح",
    "inv.cogs.history":        "سجل الفترات المقفولة",
    "inv.cogs.col.period":     "الفترة",
    "inv.cogs.col.openingInv": "مخزون الافتتاح",
    "inv.cogs.col.purchases":  "+ المشتريات",
    "inv.cogs.col.closingInv": "− مخزون الإغلاق",
    "inv.cogs.col.cogs":       "= تكلفة البضاعة المباعة",
    "inv.cogs.col.lockedBy":   "مُقفَل بواسطة",
    "inv.cogs.col.date":       "التاريخ",
    "inv.audit.searchPlaceholder": "ابحث بالكيان أو المستخدم أو التفاصيل...",
    "inv.audit.total":         "{n} إجمالي الإدخالات",
    "inv.audit.shown":         "{n} معروض",
    "inv.audit.latest":        "الأحدث:",
    "inv.audit.empty":         "لا توجد إدخالات مراجعة بعد",
    "inv.audit.emptySub":      "ستظهر هنا جميع تغييرات المخزون والموافقات وإغلاقات الفترات",
    "inv.audit.noMatch":       "لا توجد إدخالات تطابق الفلاتر.",
    "inv.audit.clearFilters":  "مسح الفلاتر",
    "inv.audit.showing":       "عرض 100 من {n} إدخال",
    "inv.audit.by":            "بواسطة",
    "inv.audit.action.all":    "الكل",
    "inv.audit.action.create": "إنشاء",
    "inv.audit.action.approve":"موافقة",
    "inv.audit.action.reject": "رفض",
    "inv.audit.action.adjustment":"تسوية",
    "inv.audit.action.close":  "إغلاق",
    "inv.audit.human.create":            "تم الإنشاء",
    "inv.audit.human.approve":           "تمت الموافقة",
    "inv.audit.human.reject":            "تم الرفض",
    "inv.audit.human.close_period":      "إغلاق الفترة",
    "inv.audit.human.adjustment":        "تسوية المخزون",
    "inv.audit.human.adjustment_approved":"تمت الموافقة على التسوية",
    "inv.audit.human.adjustment_rejected":"تم رفض التسوية",
    "inv.audit.human.create_period_snapshot":"قفل اللقطة",
    "inv.audit.entity.sale":             "بيع",
    "inv.audit.entity.purchase":         "شراء",
    "inv.audit.entity.transfer":         "تحويل",
    "inv.audit.entity.approval_request": "موافقة",
    "inv.audit.entity.inventory_movement":"حركة مخزون",
    "inv.audit.entity.period_closure":   "إغلاق فترة",
    "inv.audit.entity.period_snapshot":  "لقطة فترة",
    "inv.audit.entity.customer_return":  "مرتجع عميل",
    "inv.audit.entity.purchase_return":  "مرتجع مشتريات",
    "inv.audit.entity.record":           "سجل",
    "inv.modal.cancel": "إلغاء",
    "inv.modal.save":   "حفظ",
    "inv.modal.selectIngredient": "اختر مكوناً...",
    "inv.modal.selectReason":     "اختر السبب...",
    "inv.modal.selectBranch":     "اختر...",
    "inv.modal.notesPlaceholder": "أي ملاحظات...",
    "inv.modal.adjNotesPlaceholder": "تفاصيل إضافية...",
    "inv.modal.transferNotesPlaceholder": "ملاحظات التحويل...",
    "inv.modal.openingNotesPlaceholder": "ملاحظات مخزون الافتتاح...",
    "inv.modal.periodNotesPlaceholder":  "ملاحظات إغلاق الفترة...",

    // ── Masters ───────────────────────────────────────────────────────────────
    "masters.title":               "البيانات الأساسية",
    "masters.subtitle":            "إدارة الفروع والأصناف والموردين والمستخدمين والأسعار",
    "masters.tab.branches":        "الفروع",
    "masters.tab.suppliers":       "الموردون",
    "masters.tab.items":           "الأصناف",
    "masters.tab.users":           "المستخدمون",
    "masters.tab.prices":          "الأسعار",
    "masters.add.branch":          "إضافة فرع",
    "masters.add.supplier":        "إضافة مورد",
    "masters.add.item":            "إضافة صنف",
    "masters.add.user":            "إضافة مستخدم",
    "masters.add.price":           "تسجيل سعر",
    "masters.modal.addBranch":     "إضافة فرع",
    "masters.modal.addSupplier":   "إضافة مورد",
    "masters.modal.addItem":       "إضافة صنف",
    "masters.modal.addUser":       "إضافة مستخدم",
    "masters.modal.recordPrice":   "💰 تسجيل سعر المورد",
    "masters.field.branchName":    "اسم الفرع *",
    "masters.field.location":      "الموقع",
    "masters.field.manager":       "اسم المدير",
    "masters.field.supplierName":  "اسم المورد *",
    "masters.field.phone":         "الهاتف",
    "masters.field.notes":         "ملاحظات",
    "masters.field.itemName":      "اسم الصنف *",
    "masters.field.sku":           "رمز الصنف",
    "masters.field.category":      "الفئة",
    "masters.field.unit":          "الوحدة *",
    "masters.field.standardCost":  "التكلفة المعيارية",
    "masters.field.salePrice":     "سعر البيع",
    "masters.field.reorderLevel":  "مستوى إعادة الطلب",
    "masters.field.username":      "اسم المستخدم *",
    "masters.field.displayName":   "الاسم الظاهر *",
    "masters.field.role":          "الدور",
    "masters.field.ingredient":    "المكوّن *",
    "masters.field.supplier":      "المورد *",
    "masters.field.price":         "السعر ({currency}) *",
    "masters.field.date":          "التاريخ *",
    "masters.field.ingredientHistory": "اختر مكوناً لعرض سجل أسعاره",
    "masters.cat.rawMaterial":     "مادة خام",
    "masters.cat.finishedGood":    "منتج نهائي",
    "masters.role.clerk":          "موظف",
    "masters.role.manager":        "مدير",
    "masters.role.admin":          "مسؤول",
    "masters.label.active":        "نشط",
    "masters.label.noPhone":       "لا يوجد هاتف",
    "masters.empty.branches":      "لا توجد فروع",
    "masters.empty.suppliers":     "لا يوجد موردون",
    "masters.empty.items":         "لا توجد أصناف",
    "masters.empty.users":         "لا يوجد مستخدمون",
    "masters.empty.prices":        "لا يوجد سجل أسعار لهذا المكوّن",
    "masters.empty.selectIngredient": "اختر مكوناً أعلاه لعرض سجل أسعاره",
    "masters.priceHistory.title":  "سجل أسعار الموردين",
    "masters.priceHistory.date":   "التاريخ",
    "masters.priceHistory.supplier": "المورد",
    "masters.priceHistory.price":  "السعر ({currency})",
    "masters.priceHistory.notes":  "ملاحظات",
    "masters.defaultPassword":     "كلمة المرور الافتراضية ستكون",
    "masters.priceNote":           "سيؤدي هذا إلى تحديث التكلفة الحالية للمكوّن تلقائياً.",
    "masters.confirm.deleteBranch":   "حذف الفرع \"{name}\"؟",
    "masters.confirm.deleteSupplier": "حذف \"{name}\"؟",
    "masters.confirm.deleteItem":     "حذف الصنف \"{name}\"؟",
    "masters.err.branchName":      "اسم الفرع مطلوب",
    "masters.err.branchSave":      "فشل حفظ الفرع. قد يكون الاسم موجوداً بالفعل.",
    "masters.err.supplierName":    "اسم المورد مطلوب",
    "masters.err.supplierSave":    "فشل حفظ المورد. قد يكون الاسم موجوداً بالفعل.",
    "masters.err.itemRequired":    "الاسم والوحدة مطلوبان",
    "masters.err.itemSave":        "فشل حفظ الصنف. قد يكون الاسم موجوداً بالفعل.",
    "masters.err.userRequired":    "اسم المستخدم والاسم الظاهر مطلوبان",
    "masters.err.userSave":        "فشل حفظ المستخدم. قد يكون الاسم موجوداً بالفعل.",
    "masters.err.selectSupplier":  "اختر مورداً",
    "masters.err.selectIngredient":"اختر مكوناً",
    "masters.err.enterPrice":      "أدخل السعر",
    "masters.err.priceSave":       "فشل حفظ السعر.",
    "masters.ph.branchName":       "مثال: المستودع المركزي",
    "masters.ph.location":         "مثال: القاهرة، مصر",
    "masters.ph.manager":          "مثال: أحمد حسن",
    "masters.ph.supplierName":     "مثال: شركة الأغذية الطازجة",
    "masters.ph.phone":            "‎+20 100 000 0000",
    "masters.ph.notes":            "أي معلومات إضافية...",
    "masters.ph.itemName":         "مثال: طماطم",
    "masters.ph.sku":              "RM-001",
    "masters.ph.unit":             "كجم / قطعة / لتر",
    "masters.ph.price":            "0.00",
    "masters.ph.priceNotes":       "مثال: سعر موسمي، خصم كميات...",
    "masters.ph.username":         "مثال: ahmed.hassan",
    "masters.ph.displayName":      "مثال: أحمد حسن",
    "masters.ph.selectIngredient": "اختر مكوناً...",
    "masters.ph.selectSupplier":   "اختر مورداً...",
    "masters.cancel":              "إلغاء",
    "masters.save":                "حفظ",
    // ── Procurement ──
    "proc.title":               "المشتريات",
    "proc.subtitle":            "أوامر الشراء والمرتجعات وأسعار الموردين",
    "proc.modal.newPurchase":   "📋 أمر شراء جديد",
    "proc.modal.return":        "↩️ مرتجع مشتريات",
    "proc.field.branch":        "الفرع *",
    "proc.field.supplier":      "المورد *",
    "proc.field.ingredient":    "المكوّن *",
    "proc.field.date":          "التاريخ *",
    "proc.field.quantity":      "الكمية *",
    "proc.field.unitCost":      "سعر الوحدة ({currency}) *",
    "proc.field.taxAmount":     "مبلغ الضريبة ({currency})",
    "proc.field.notes":         "ملاحظات",
    "proc.field.unitCostShort": "سعر الوحدة *",
    "proc.summary.gross":       "المبلغ الإجمالي",
    "proc.summary.tax":         "الضريبة",
    "proc.summary.payable":     "إجمالي المستحق",
    "proc.summary.refund":      "مبلغ الاسترداد",
    "proc.ph.selectBranch":     "اختر فرعاً...",
    "proc.ph.selectSupplier":   "اختر مورداً...",
    "proc.ph.selectIngredient": "اختر مكوناً...",
    "proc.ph.notes":            "أي ملاحظات إضافية...",
    "proc.ph.returnNotes":      "سبب الإرجاع...",
    "proc.err.branch":          "اختر فرعاً",
    "proc.err.supplier":        "اختر مورداً",
    "proc.err.ingredient":      "اختر مكوناً",
    "proc.err.quantity":        "أدخل الكمية",
    "proc.err.unitCost":        "أدخل سعر الوحدة",
    "proc.err.savePurchase":    "فشل حفظ المشتريات. حاول مرة أخرى.",
    "proc.err.saveReturn":      "فشل حفظ المرتجع. حاول مرة أخرى.",
    "proc.kpi.totalPurchases":  "إجمالي المشتريات",
    "proc.kpi.allTime":         "كل الوقت",
    "proc.kpi.thisMonth":       "هذا الشهر",
    "proc.kpi.activeSuppliers": "الموردون النشطون",
    "proc.kpi.inSystem":        "في النظام",
    "proc.ops.title":           "عمليات الشراء",
    "proc.ops.purchase":        "أمر شراء",
    "proc.ops.purchaseDesc":    "تسجيل مخزون جديد مستلم من المورد",
    "proc.ops.return":          "مرتجع مشتريات",
    "proc.ops.returnDesc":      "إرجاع بضاعة تالفة أو خاطئة للمورد",
    "proc.ops.record":          "تسجيل",
    "proc.suppliers.title":     "الموردون",
    "proc.suppliers.empty":     "لا يوجد موردون بعد",
    "proc.recent.title":        "المشتريات الأخيرة",
    "proc.recent.empty":        "لم يتم تسجيل أي مشتريات بعد",
    "proc.recent.firstCta":     "تسجيل أول عملية شراء",
    "proc.table.date":          "التاريخ",
    "proc.table.branch":        "الفرع",
    "proc.table.ingredient":    "المكوّن",
    "proc.table.supplier":      "المورد",
    "proc.table.qty":           "الكمية",
    "proc.table.unitCost":      "سعر الوحدة",
    "proc.table.total":         "الإجمالي",
    "proc.table.status":        "الحالة",
    "proc.cancel":              "إلغاء",
    "proc.save":                "حفظ",
    // ── Production ──
    "prod.title":                "الإنتاج",
    "prod.subtitle":             "إصدارات المطبخ والتحويلات ودفعات الإنتاج",
    "prod.modal.kitchen":        "🍳 إصدار مطبخ",
    "prod.modal.transfer":       "↔️ تحويل مخزون",
    "prod.modal.production":     "🏭 دفعة إنتاج",
    "prod.field.branch":         "الفرع *",
    "prod.field.ingredient":     "المكوّن *",
    "prod.field.date":           "التاريخ *",
    "prod.field.qtyIssued":      "الكمية المُصدَرة *",
    "prod.field.station":        "المحطة *",
    "prod.field.notes":          "ملاحظات",
    "prod.field.fromBranch":     "من الفرع *",
    "prod.field.toBranch":       "إلى الفرع *",
    "prod.field.quantity":       "الكمية *",
    "prod.field.product":        "المنتج (منتج نهائي) *",
    "prod.field.qtyProduced":    "الكمية المُنتَجة *",
    "prod.field.laborCost":      "تكلفة العمالة المباشرة ({currency})",
    "prod.field.overheadCost":   "تكلفة المصاريف العامة ({currency})",
    "prod.ph.selectBranch":      "اختر فرعاً...",
    "prod.ph.selectIngredient":  "اختر مكوناً...",
    "prod.ph.selectBranchShort": "اختر...",
    "prod.ph.selectProduct":     "اختر منتجاً...",
    "prod.ph.station":           "مثال: محطة الشواء، المطبخ البارد، التحضير",
    "prod.ph.notes":             "أي ملاحظات إضافية...",
    "prod.ph.transferNotes":     "سبب التحويل...",
    "prod.ph.productionNotes":   "ملاحظات الإنتاج...",
    "prod.note.kitchen":         "سيتم خصم الكمية من رصيد مخزون الفرع فوراً.",
    "prod.note.transfer":        "سيتم خصم المخزون من الفرع المصدر وإضافته إلى الفرع الوجهة.",
    "prod.err.branch":           "اختر فرعاً",
    "prod.err.ingredient":       "اختر مكوناً",
    "prod.err.quantity":         "أدخل الكمية",
    "prod.err.station":          "أدخل اسم المحطة",
    "prod.err.fromBranch":       "اختر الفرع المصدر",
    "prod.err.toBranch":         "اختر الفرع الوجهة",
    "prod.err.sameBranch":       "يجب أن يختلف المصدر عن الوجهة",
    "prod.err.product":          "اختر منتجاً",
    "prod.err.saveKitchen":      "فشل حفظ إصدار المطبخ. حاول مرة أخرى.",
    "prod.err.saveTransfer":     "فشل حفظ التحويل. حاول مرة أخرى.",
    "prod.err.saveProduction":   "فشل حفظ دفعة الإنتاج. حاول مرة أخرى.",
    "prod.kpi.recipes":          "الوصفات",
    "prod.kpi.recipesDesc":      "منتجات نهائية",
    "prod.kpi.batches":          "دفعات الإنتاج",
    "prod.kpi.batchesDesc":      "كل الوقت",
    "prod.kpi.thisMonth":        "هذا الشهر",
    "prod.kpi.thisMonthDesc":    "دورات إنتاج",
    "prod.kpi.kitchenIssues":    "إصدارات المطبخ",
    "prod.kpi.kitchenIssuesDesc":"إجمالي المسجلة",
    "prod.ops.title":            "عمليات الإنتاج",
    "prod.ops.kitchen":          "إصدار مطبخ",
    "prod.ops.kitchenDesc":      "إصدار مكونات لمحطة مطبخ للطهي",
    "prod.ops.transfer":         "تحويل مخزون",
    "prod.ops.transferDesc":     "نقل المخزون بين الفروع (مثال: المستودع ← الفرع)",
    "prod.ops.production":       "دفعة إنتاج",
    "prod.ops.productionDesc":   "تسجيل دورة إنتاج فعلية بتكاليف العمالة والمصاريف العامة",
    "prod.ops.record":           "تسجيل",
    "prod.products.title":       "المنتجات",
    "prod.products.empty":       "لا توجد منتجات بعد",
    "prod.recent.title":         "النشاط الأخير",
    "prod.tab.kitchen":          "إصدارات المطبخ",
    "prod.tab.production":       "الإنتاج",
    "prod.tab.transfers":        "التحويلات",
    "prod.kitchen.empty":        "لم يتم تسجيل أي إصدارات مطبخ بعد",
    "prod.kitchen.cta":          "تسجيل إصدار مطبخ",
    "prod.production.empty":     "لم يتم تسجيل أي دفعات إنتاج بعد",
    "prod.production.cta":       "تسجيل دفعة إنتاج",
    "prod.transfers.empty":      "لم يتم تسجيل أي تحويلات بعد",
    "prod.transfers.cta":        "تسجيل تحويل",
    "prod.table.date":           "التاريخ",
    "prod.table.branch":         "الفرع",
    "prod.table.ingredient":     "المكوّن",
    "prod.table.station":        "المحطة",
    "prod.table.qtyIssued":      "الكمية المُصدَرة",
    "prod.table.notes":          "ملاحظات",
    "prod.table.product":        "المنتج",
    "prod.table.quantity":       "الكمية",
    "prod.table.material":       "المواد",
    "prod.table.labor":          "العمالة",
    "prod.table.totalCost":      "إجمالي التكلفة",
    "prod.table.from":           "من",
    "prod.table.to":             "إلى",
    "prod.table.status":         "الحالة",
    "prod.cancel":               "إلغاء",
    "prod.save":                 "حفظ",

    // ── Recipes ───────────────────────────────────────────────────────────────
    "recipes.title":                   "الوصفات",
    "recipes.subtitle":                "تعريف المكونات والتكاليف لكل منتج",
    "recipes.kpi.totalProducts":       "إجمالي المنتجات",
    "recipes.kpi.totalProductsSub":    "منتجات نهائية",
    "recipes.kpi.ingredients":         "المكونات",
    "recipes.kpi.ingredientsSub":      "مواد خام",
    "recipes.kpi.tip":                 "💡 نصيحة",
    "recipes.kpi.tipText":             "انقر على أي منتج لعرض وصفته. استخدم تصدير PDF لتنزيل ورقة الوصفة.",
    "recipes.search.placeholder":      "ابحث عن منتجات بالاسم…",
    "recipes.filter.all":              "الكل",
    "recipes.filter.hasRecipe":        "✅ لها وصفة",
    "recipes.filter.noRecipe":         "⚠️ بلا وصفة",
    "recipes.list.title":              "المنتجات والوصفات",
    "recipes.list.showing":            "عرض {shown} من {total} منتج",
    "recipes.list.empty.search":       "لا توجد منتجات تطابق \"{search}\".",
    "recipes.list.empty.default":      "لا توجد منتجات. أضف منتجات في البيانات الأساسية أولاً.",
    "recipes.card.clickToLoad":        "انقر للتحميل",
    "recipes.card.hasRecipe":          "لها وصفة",
    "recipes.card.noRecipe":           "بلا وصفة",
    "recipes.card.sale":               "البيع",
    "recipes.card.noRecipeDefined":    "لم يتم تعريف وصفة لهذا المنتج بعد.",
    "recipes.card.yield":              "المردود",
    "recipes.card.portion":            "الحصة",
    "recipes.card.foodCostPct":        "نسبة تكلفة الغذاء",
    "recipes.card.rawCostPerPortion":  "التكلفة الخام / الحصة",
    "recipes.card.grossMargin":        "هامش الربح الإجمالي",
    "recipes.card.ingredients":        "المكونات",
    "recipes.card.col.ingredient":     "المكوّن",
    "recipes.card.col.qtyRequired":    "الكمية المطلوبة",
    "recipes.card.col.unitCost":       "تكلفة الوحدة",
    "recipes.card.col.lineCost":       "تكلفة السطر",
    "recipes.card.notes":              "📝 ملاحظات",
    "recipes.card.addIngredient":      "إضافة مكوّن",
    "recipes.card.editRecipe":         "تعديل الوصفة",
    "recipes.card.exportPdf":          "تصدير PDF",
    "recipes.card.delete":             "حذف",
    "recipes.card.createRecipe":       "إنشاء وصفة",
    "recipes.confirm.deleteMessage":   "سيؤدي هذا إلى حذف وصفة \"{name}\" وجميع مكوناتها نهائياً.",
    "recipes.modal.createTitle":       "📋 إنشاء وصفة — {name}",
    "recipes.modal.editTitle":         "✏️ تعديل وصفة — {name}",
    "recipes.modal.addIngredientTitle":"➕ إضافة مكوّن — {name}",
    "recipes.modal.product":           "المنتج:",
    "recipes.modal.salePrice":         "سعر البيع:",
    "recipes.modal.yieldPct":          "المردود % *",
    "recipes.modal.portionSize":       "حجم الحصة *",
    "recipes.modal.portionUnit":       "وحدة الحصة *",
    "recipes.modal.notes":             "ملاحظات",
    "recipes.modal.notesPh":           "ملاحظات الوصفة...",
    "recipes.modal.afterCreate":       "بعد إنشاء الوصفة، يمكنك إضافة المكونات إليها.",
    "recipes.modal.ingredient":        "المكوّن *",
    "recipes.modal.selectIngredient":  "اختر مكوناً...",
    "recipes.modal.qtyRequired":       "الكمية المطلوبة لكل حصة *",
    "recipes.modal.qtyPh":             "مثال: 0.300 لـ 300 جرام",
    "recipes.modal.lineCost":          "تكلفة السطر: {cost} لكل حصة",
    "recipes.modal.qtyNote":           "هذه هي الكمية المطلوبة من هذا المكوّن لتحضير حصة واحدة من {product}.",
    "recipes.err.yieldRange":          "يجب أن يكون المردود % بين 1 و100",
    "recipes.err.portionSize":         "يجب أن يكون حجم الحصة أكبر من صفر",
    "recipes.err.portionUnit":         "وحدة الحصة مطلوبة",
    "recipes.err.saveFailed":          "فشل حفظ الوصفة. حاول مرة أخرى.",
    "recipes.err.updateFailed":        "فشل تحديث الوصفة.",
    "recipes.err.selectIngredient":    "اختر مكوناً",
    "recipes.err.qtyPositive":         "يجب أن تكون الكمية أكبر من صفر",
    "recipes.err.addIngredientFailed": "فشل إضافة المكوّن. قد يكون موجوداً بالفعل في هذه الوصفة.",
    "recipes.unit.plate":              "طبق",
    "recipes.unit.box":                "علبة",
    "recipes.unit.cup":                "كوب",
    "recipes.unit.bowl":               "وعاء",
    "recipes.unit.serving":            "حصة",
    "recipes.unit.piece":              "قطعة",
    "recipes.unit.kg":                 "كجم",
    "recipes.unit.litre":              "لتر",
    "recipes.confirm.areYouSure":      "هل أنت متأكد؟",
    "recipes.confirm.delete":          "حذف",
    "recipes.confirm.cancel":          "إلغاء",
    "recipes.modal.save":              "حفظ",
    "recipes.modal.cancel":            "إلغاء",

    // ── Governance ────────────────────────────────────────────────────────────
    "gov.title":                       "الحوكمة",
    "gov.subtitle":                    "الموافقات وإغلاق الفترات وضوابط المراجعة",
    "gov.metric.pendingApprovals":     "الموافقات المعلقة",
    "gov.metric.pendingApprovalsSub":  "بانتظار المراجعة",
    "gov.metric.approvedThisMonth":    "تمت الموافقة هذا الشهر",
    "gov.metric.approvedThisMonthSub": "نسبة موافقة 94%",
    "gov.metric.openPeriods":          "الفترات المفتوحة",
    "gov.metric.openPeriodsSub":       "الحالية: أبريل 2026",
    "gov.ops.title":                   "عمليات الحوكمة",
    "gov.ops.pendingApprovals":        "الموافقات المعلقة",
    "gov.ops.pendingApprovalsDesc":    "مراجعة والموافقة على المعاملات المعلقة",
    "gov.ops.periodClosing":           "إغلاق الفترة",
    "gov.ops.periodClosingDesc":       "إغلاق فترة المحاسبة",
    "gov.ops.auditTrail":              "سجل المراجعة",
    "gov.ops.auditTrailDesc":          "عرض سجل المعاملات والتغييرات",
    "gov.ops.budgetManagement":        "إدارة الميزانية",
    "gov.ops.budgetManagementDesc":    "تعيين ومتابعة الميزانيات",
    "gov.approvalStatus.title":        "حالة الموافقات",
    "gov.approvalStatus.pending":      "معلّق",
    "gov.approvalStatus.approved":     "تمت الموافقة",
    "gov.status.purchases":            "المشتريات",
    "gov.status.expenses":             "المصروفات",
    "gov.status.adjustments":          "التسويات",
    "gov.status.transfers":            "التحويلات",
    "gov.pending.title":               "الموافقات المعلقة",
    "gov.pending.submittedBy":         "قُدِّم بواسطة",
    "gov.pending.reject":              "رفض",
    "gov.pending.approve":             "موافقة",
    "gov.approvalType.purchase":       "أمر شراء",
    "gov.approvalType.expense":        "مصروف",
    "gov.approvalType.stockAdj":       "تسوية مخزون",
    "gov.approvalType.transfer":       "تحويل",
    "gov.role.manager":                "مدير",
    "gov.role.admin":                  "مسؤول",
    "gov.role.accountant":             "محاسب",
    "gov.period.current":              "الفترة الحالية: أبريل 2026",
    "gov.period.note":                 "الفترة مفتوحة. يتم تسجيل جميع المعاملات. أغلق الفترة عند اكتمال جميع القيود.",
    "gov.period.close":                "إغلاق الفترة",
    "gov.period.closed":               "الفترة مغلقة: أبريل 2026",
    "gov.period.closedNote":           "تم قفل هذه الفترة. لا يمكن إضافة قيود جديدة.",
    "gov.period.closedBadge":          "مغلقة",
    "gov.pending.allReviewed":         "تمت مراجعة جميع العناصر.",
    "gov.pending.approved":            "تمت الموافقة",
    "gov.pending.rejected":            "تم الرفض",
    "gov.metric.openPeriodsClosed":    "لا توجد فترات مفتوحة",
  },
};

const LanguageContext = createContext<LanguageContextValue>({
  language:       "en",
  toggleLanguage: () => {},
  isRTL:          false,
  t:              (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const storedLanguage = localStorage.getItem("lang");
    return isAppLanguage(storedLanguage) ? storedLanguage : "en";
  });

  const isRTL = language === "ar";

  useEffect(() => {
    const html = document.documentElement;
    html.setAttribute("dir",  isRTL ? "rtl" : "ltr");
    html.setAttribute("lang", language);
    html.style.fontFamily = isRTL
      ? "'Cairo', 'Segoe UI', Tahoma, Arial, sans-serif"
      : "";
    localStorage.setItem("lang", language);
  }, [language, isRTL]);

  function toggleLanguage() {
    setLanguage(l => (l === "en" ? "ar" : "en"));
  }

  function t(key: string): string {
    return translations[language][key] ?? translations["en"][key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}