name: Release Pipeline

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show version
        run: |
          echo "BUILD VERSION: $GITHUB_REF_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2